// Code generated by ent, DO NOT EDIT.

package fulfillment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldDeletedAt, v))
}

// CommerceOrderID applies equality check predicate on the "commerce_order_id" field. It's identical to CommerceOrderIDEQ.
func CommerceOrderID(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCommerceOrderID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCustomerID, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldClaimedAt, v))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldGrantID, v))
}

// CreditsGranted applies equality check predicate on the "credits_granted" field. It's identical to CreditsGrantedEQ.
func CreditsGranted(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreditsGranted, v))
}

// FulfilledAt applies equality check predicate on the "fulfilled_at" field. It's identical to FulfilledAtEQ.
func FulfilledAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldFulfilledAt, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldFailureReason, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldDeletedAt))
}

// CommerceOrderIDEQ applies the EQ predicate on the "commerce_order_id" field.
func CommerceOrderIDEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCommerceOrderID, v))
}

// CommerceOrderIDNEQ applies the NEQ predicate on the "commerce_order_id" field.
func CommerceOrderIDNEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldCommerceOrderID, v))
}

// CommerceOrderIDIn applies the In predicate on the "commerce_order_id" field.
func CommerceOrderIDIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldCommerceOrderID, vs...))
}

// CommerceOrderIDNotIn applies the NotIn predicate on the "commerce_order_id" field.
func CommerceOrderIDNotIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldCommerceOrderID, vs...))
}

// CommerceOrderIDGT applies the GT predicate on the "commerce_order_id" field.
func CommerceOrderIDGT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldCommerceOrderID, v))
}

// CommerceOrderIDGTE applies the GTE predicate on the "commerce_order_id" field.
func CommerceOrderIDGTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldCommerceOrderID, v))
}

// CommerceOrderIDLT applies the LT predicate on the "commerce_order_id" field.
func CommerceOrderIDLT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldCommerceOrderID, v))
}

// CommerceOrderIDLTE applies the LTE predicate on the "commerce_order_id" field.
func CommerceOrderIDLTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldCommerceOrderID, v))
}

// CommerceOrderIDContains applies the Contains predicate on the "commerce_order_id" field.
func CommerceOrderIDContains(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContains(FieldCommerceOrderID, v))
}

// CommerceOrderIDHasPrefix applies the HasPrefix predicate on the "commerce_order_id" field.
func CommerceOrderIDHasPrefix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasPrefix(FieldCommerceOrderID, v))
}

// CommerceOrderIDHasSuffix applies the HasSuffix predicate on the "commerce_order_id" field.
func CommerceOrderIDHasSuffix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasSuffix(FieldCommerceOrderID, v))
}

// CommerceOrderIDEqualFold applies the EqualFold predicate on the "commerce_order_id" field.
func CommerceOrderIDEqualFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldCommerceOrderID, v))
}

// CommerceOrderIDContainsFold applies the ContainsFold predicate on the "commerce_order_id" field.
func CommerceOrderIDContainsFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldCommerceOrderID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldCustomerID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldStatus, vs...))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldClaimedAt, v))
}

// ClaimedAtIsNil applies the IsNil predicate on the "claimed_at" field.
func ClaimedAtIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldClaimedAt))
}

// ClaimedAtNotNil applies the NotNil predicate on the "claimed_at" field.
func ClaimedAtNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldClaimedAt))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldGrantID, vs...))
}

// GrantIDGT applies the GT predicate on the "grant_id" field.
func GrantIDGT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldGrantID, v))
}

// GrantIDGTE applies the GTE predicate on the "grant_id" field.
func GrantIDGTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldGrantID, v))
}

// GrantIDLT applies the LT predicate on the "grant_id" field.
func GrantIDLT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldGrantID, v))
}

// GrantIDLTE applies the LTE predicate on the "grant_id" field.
func GrantIDLTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldGrantID, v))
}

// GrantIDContains applies the Contains predicate on the "grant_id" field.
func GrantIDContains(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContains(FieldGrantID, v))
}

// GrantIDHasPrefix applies the HasPrefix predicate on the "grant_id" field.
func GrantIDHasPrefix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasPrefix(FieldGrantID, v))
}

// GrantIDHasSuffix applies the HasSuffix predicate on the "grant_id" field.
func GrantIDHasSuffix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasSuffix(FieldGrantID, v))
}

// GrantIDIsNil applies the IsNil predicate on the "grant_id" field.
func GrantIDIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldGrantID))
}

// GrantIDNotNil applies the NotNil predicate on the "grant_id" field.
func GrantIDNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldGrantID))
}

// GrantIDEqualFold applies the EqualFold predicate on the "grant_id" field.
func GrantIDEqualFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldGrantID, v))
}

// GrantIDContainsFold applies the ContainsFold predicate on the "grant_id" field.
func GrantIDContainsFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldGrantID, v))
}

// CreditsGrantedEQ applies the EQ predicate on the "credits_granted" field.
func CreditsGrantedEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreditsGranted, v))
}

// CreditsGrantedNEQ applies the NEQ predicate on the "credits_granted" field.
func CreditsGrantedNEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldCreditsGranted, v))
}

// CreditsGrantedIn applies the In predicate on the "credits_granted" field.
func CreditsGrantedIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldCreditsGranted, vs...))
}

// CreditsGrantedNotIn applies the NotIn predicate on the "credits_granted" field.
func CreditsGrantedNotIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldCreditsGranted, vs...))
}

// CreditsGrantedGT applies the GT predicate on the "credits_granted" field.
func CreditsGrantedGT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldCreditsGranted, v))
}

// CreditsGrantedGTE applies the GTE predicate on the "credits_granted" field.
func CreditsGrantedGTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldCreditsGranted, v))
}

// CreditsGrantedLT applies the LT predicate on the "credits_granted" field.
func CreditsGrantedLT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldCreditsGranted, v))
}

// CreditsGrantedLTE applies the LTE predicate on the "credits_granted" field.
func CreditsGrantedLTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldCreditsGranted, v))
}

// FulfilledAtEQ applies the EQ predicate on the "fulfilled_at" field.
func FulfilledAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldFulfilledAt, v))
}

// FulfilledAtNEQ applies the NEQ predicate on the "fulfilled_at" field.
func FulfilledAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldFulfilledAt, v))
}

// FulfilledAtIn applies the In predicate on the "fulfilled_at" field.
func FulfilledAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldFulfilledAt, vs...))
}

// FulfilledAtNotIn applies the NotIn predicate on the "fulfilled_at" field.
func FulfilledAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldFulfilledAt, vs...))
}

// FulfilledAtGT applies the GT predicate on the "fulfilled_at" field.
func FulfilledAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldFulfilledAt, v))
}

// FulfilledAtGTE applies the GTE predicate on the "fulfilled_at" field.
func FulfilledAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldFulfilledAt, v))
}

// FulfilledAtLT applies the LT predicate on the "fulfilled_at" field.
func FulfilledAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldFulfilledAt, v))
}

// FulfilledAtLTE applies the LTE predicate on the "fulfilled_at" field.
func FulfilledAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldFulfilledAt, v))
}

// FulfilledAtIsNil applies the IsNil predicate on the "fulfilled_at" field.
func FulfilledAtIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldFulfilledAt))
}

// FulfilledAtNotNil applies the NotNil predicate on the "fulfilled_at" field.
func FulfilledAtNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldFulfilledAt))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldFailureReason, v))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.Fulfillment {
	return predicate.Fulfillment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.CommerceOrder) predicate.Fulfillment {
	return predicate.Fulfillment(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Fulfillment) predicate.Fulfillment {
	return predicate.Fulfillment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Fulfillment) predicate.Fulfillment {
	return predicate.Fulfillment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Fulfillment) predicate.Fulfillment {
	return predicate.Fulfillment(sql.NotPredicates(p))
}
