// Code generated by ent, DO NOT EDIT.

package aiusageoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the aiusageoutbox type in the database.
	Label = "ai_usage_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldSubjectID holds the string denoting the subject_id field in the database.
	FieldSubjectID = "subject_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldPublished holds the string denoting the published field in the database.
	FieldPublished = "published"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldClaimCount holds the string denoting the claim_count field in the database.
	FieldClaimCount = "claim_count"
	// FieldLeasedUntil holds the string denoting the leased_until field in the database.
	FieldLeasedUntil = "leased_until"
	// FieldDeadLettered holds the string denoting the dead_lettered field in the database.
	FieldDeadLettered = "dead_lettered"
	// FieldDeadLetterReason holds the string denoting the dead_letter_reason field in the database.
	FieldDeadLetterReason = "dead_letter_reason"
	// EdgeBatch holds the string denoting the batch edge name in mutations.
	EdgeBatch = "batch"
	// Table holds the table name of the aiusageoutbox in the database.
	Table = "ai_usage_outboxes"
	// BatchTable is the table that holds the batch relation/edge.
	BatchTable = "ai_usage_outboxes"
	// BatchInverseTable is the table name for the AIUsageBatch entity.
	// It exists in this package in order to avoid circular dependency with the "aiusagebatch" package.
	BatchInverseTable = "ai_usage_batches"
	// BatchColumn is the table column denoting the batch relation/edge.
	BatchColumn = "ai_usage_batch_outbox_events"
)

// Columns holds all SQL columns for aiusageoutbox fields.
var Columns = []string{
	FieldID,
	FieldNamespace,
	FieldCreatedAt,
	FieldCustomerID,
	FieldSubjectID,
	FieldEventType,
	FieldPayload,
	FieldPublished,
	FieldPublishedAt,
	FieldOwner,
	FieldClaimCount,
	FieldLeasedUntil,
	FieldDeadLettered,
	FieldDeadLetterReason,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ai_usage_outboxes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ai_usage_batch_outbox_events",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	NamespaceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	CustomerIDValidator func(string) error
	// SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	SubjectIDValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultPublished holds the default value on creation for the "published" field.
	DefaultPublished bool
	// DefaultOwner holds the default value on creation for the "owner" field.
	DefaultOwner string
	// DefaultClaimCount holds the default value on creation for the "claim_count" field.
	DefaultClaimCount int
	// DefaultDeadLettered holds the default value on creation for the "dead_lettered" field.
	DefaultDeadLettered bool
	// DefaultDeadLetterReason holds the default value on creation for the "dead_letter_reason" field.
	DefaultDeadLetterReason string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the AIUsageOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// BySubjectID orders the results by the subject_id field.
func BySubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByPublished orders the results by the published field.
func ByPublished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublished, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByClaimCount orders the results by the claim_count field.
func ByClaimCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimCount, opts...).ToFunc()
}

// ByLeasedUntil orders the results by the leased_until field.
func ByLeasedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeasedUntil, opts...).ToFunc()
}

// ByDeadLettered orders the results by the dead_lettered field.
func ByDeadLettered(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeadLettered, opts...).ToFunc()
}

// ByDeadLetterReason orders the results by the dead_letter_reason field.
func ByDeadLetterReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeadLetterReason, opts...).ToFunc()
}

// ByBatchField orders the results by batch field.
func ByBatchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBatchStep(), sql.OrderByField(field, opts...))
	}
}
func newBatchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BatchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BatchTable, BatchColumn),
	)
}
