// Code generated by ent, DO NOT EDIT.

package commerceproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldDeletedAt, v))
}

// Sku applies equality check predicate on the "sku" field. It's identical to SkuEQ.
func Sku(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldSku, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldName, v))
}

// PriceCents applies equality check predicate on the "price_cents" field. It's identical to PriceCentsEQ.
func PriceCents(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldPriceCents, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldCurrency, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldDescription, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContainsFold(FieldNamespace, v))
}

// AnnotationsIsNil applies the IsNil predicate on the "annotations" field.
func AnnotationsIsNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIsNull(FieldAnnotations))
}

// AnnotationsNotNil applies the NotNil predicate on the "annotations" field.
func AnnotationsNotNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotNull(FieldAnnotations))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotNull(FieldDeletedAt))
}

// SkuEQ applies the EQ predicate on the "sku" field.
func SkuEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldSku, v))
}

// SkuNEQ applies the NEQ predicate on the "sku" field.
func SkuNEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldSku, v))
}

// SkuIn applies the In predicate on the "sku" field.
func SkuIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldSku, vs...))
}

// SkuNotIn applies the NotIn predicate on the "sku" field.
func SkuNotIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldSku, vs...))
}

// SkuGT applies the GT predicate on the "sku" field.
func SkuGT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldSku, v))
}

// SkuGTE applies the GTE predicate on the "sku" field.
func SkuGTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldSku, v))
}

// SkuLT applies the LT predicate on the "sku" field.
func SkuLT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldSku, v))
}

// SkuLTE applies the LTE predicate on the "sku" field.
func SkuLTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldSku, v))
}

// SkuContains applies the Contains predicate on the "sku" field.
func SkuContains(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContains(FieldSku, v))
}

// SkuHasPrefix applies the HasPrefix predicate on the "sku" field.
func SkuHasPrefix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasPrefix(FieldSku, v))
}

// SkuHasSuffix applies the HasSuffix predicate on the "sku" field.
func SkuHasSuffix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasSuffix(FieldSku, v))
}

// SkuEqualFold applies the EqualFold predicate on the "sku" field.
func SkuEqualFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEqualFold(FieldSku, v))
}

// SkuContainsFold applies the ContainsFold predicate on the "sku" field.
func SkuContainsFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContainsFold(FieldSku, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldKind, vs...))
}

// PriceCentsEQ applies the EQ predicate on the "price_cents" field.
func PriceCentsEQ(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldPriceCents, v))
}

// PriceCentsNEQ applies the NEQ predicate on the "price_cents" field.
func PriceCentsNEQ(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldPriceCents, v))
}

// PriceCentsIn applies the In predicate on the "price_cents" field.
func PriceCentsIn(vs ...int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldPriceCents, vs...))
}

// PriceCentsNotIn applies the NotIn predicate on the "price_cents" field.
func PriceCentsNotIn(vs ...int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldPriceCents, vs...))
}

// PriceCentsGT applies the GT predicate on the "price_cents" field.
func PriceCentsGT(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldPriceCents, v))
}

// PriceCentsGTE applies the GTE predicate on the "price_cents" field.
func PriceCentsGTE(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldPriceCents, v))
}

// PriceCentsLT applies the LT predicate on the "price_cents" field.
func PriceCentsLT(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldPriceCents, v))
}

// PriceCentsLTE applies the LTE predicate on the "price_cents" field.
func PriceCentsLTE(v int64) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldPriceCents, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContainsFold(FieldCurrency, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldContainsFold(FieldDescription, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommerceProduct) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommerceProduct) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommerceProduct) predicate.CommerceProduct {
	return predicate.CommerceProduct(sql.NotPredicates(p))
}
