// Code generated by @openmeter/typespec-typescript. DO NOT EDIT.

import { type Client, http } from '../core.js'
import { type Result, type RequestOptions } from '../lib/types.js'
import { request } from '../lib/request.js'
import { toWire, toPathWire, fromWire, assertValid } from '../lib/wire.js'
import * as schemas from '../models/schemas.js'
import type {
  CreateCreditReservationRequest,
  CreateCreditReservationResponse,
  GetCreditReservationRequest,
  GetCreditReservationResponse,
  ExecuteCreditReservationRequest,
  ExecuteCreditReservationResponse,
  SettleCreditReservationRequest,
  SettleCreditReservationResponse,
  ReleaseCreditReservationRequest,
  ReleaseCreditReservationResponse,
  MarkCreditReservationUnknownRequest,
  MarkCreditReservationUnknownResponse,
  CreateCreditChargeRequest,
  CreateCreditChargeResponse,
  ReverseCreditChargeRequest,
  ReverseCreditChargeResponse,
} from '../models/operations/creditReservations.js'

/**
 * Create a credit reservation
 *
 * POST /credit-reservations
 */
export function createCreditReservation(
  client: Client,
  req: CreateCreditReservationRequest,
  options?: RequestOptions,
): Promise<Result<CreateCreditReservationResponse>> {
  return request(() => {
    const body = toWire(req, schemas.createCreditReservationBody)
    if (client._options.validate) {
      assertValid(schemas.createCreditReservationBodyWire, body)
    }
    return http(client)
      .post('credit-reservations', { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.createCreditReservationResponseWire, data)
        }
        return fromWire(data, schemas.createCreditReservationResponse)
      })
  })
}

/**
 * Get a credit reservation
 *
 * GET /credit-reservations/{reservationId}
 */
export function getCreditReservation(
  client: Client,
  req: GetCreditReservationRequest,
  options?: RequestOptions,
): Promise<Result<GetCreditReservationResponse>> {
  return request(() => {
    const pathParamsInput = {
      reservationId: req.reservationId,
    }
    const pathParams = client._options.validate
      ? toPathWire(pathParamsInput, schemas.getCreditReservationPathParams)
      : pathParamsInput
    if (client._options.validate) {
      assertValid(schemas.getCreditReservationPathParamsWire, pathParams)
    }
    const path = `credit-reservations/${(() => { if (pathParams.reservationId === undefined) { throw new Error('missing path parameter: reservationId') } return encodeURIComponent(String(pathParams.reservationId)) })()}`
    return http(client)
      .get(path, options)
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.getCreditReservationResponseWire, data)
        }
        return fromWire(data, schemas.getCreditReservationResponse)
      })
  })
}

/**
 * Start executing a credit reservation
 *
 * POST /credit-reservations/{reservationId}/execute
 */
export function executeCreditReservation(
  client: Client,
  req: ExecuteCreditReservationRequest,
  options?: RequestOptions,
): Promise<Result<ExecuteCreditReservationResponse>> {
  return request(() => {
    const pathParamsInput = {
      reservationId: req.reservationId,
    }
    const pathParams = client._options.validate
      ? toPathWire(pathParamsInput, schemas.executeCreditReservationPathParams)
      : pathParamsInput
    if (client._options.validate) {
      assertValid(schemas.executeCreditReservationPathParamsWire, pathParams)
    }
    const path = `credit-reservations/${(() => { if (pathParams.reservationId === undefined) { throw new Error('missing path parameter: reservationId') } return encodeURIComponent(String(pathParams.reservationId)) })()}/execute`
    const body = toWire(req.body, schemas.executeCreditReservationBody)
    if (client._options.validate) {
      assertValid(schemas.executeCreditReservationBodyWire, body)
    }
    return http(client)
      .post(path, { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.executeCreditReservationResponseWire, data)
        }
        return fromWire(data, schemas.executeCreditReservationResponse)
      })
  })
}

/**
 * Settle a credit reservation
 *
 * POST /credit-reservations/{reservationId}/settle
 */
export function settleCreditReservation(
  client: Client,
  req: SettleCreditReservationRequest,
  options?: RequestOptions,
): Promise<Result<SettleCreditReservationResponse>> {
  return request(() => {
    const pathParamsInput = {
      reservationId: req.reservationId,
    }
    const pathParams = client._options.validate
      ? toPathWire(pathParamsInput, schemas.settleCreditReservationPathParams)
      : pathParamsInput
    if (client._options.validate) {
      assertValid(schemas.settleCreditReservationPathParamsWire, pathParams)
    }
    const path = `credit-reservations/${(() => { if (pathParams.reservationId === undefined) { throw new Error('missing path parameter: reservationId') } return encodeURIComponent(String(pathParams.reservationId)) })()}/settle`
    const body = toWire(req.body, schemas.settleCreditReservationBody)
    if (client._options.validate) {
      assertValid(schemas.settleCreditReservationBodyWire, body)
    }
    return http(client)
      .post(path, { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.settleCreditReservationResponseWire, data)
        }
        return fromWire(data, schemas.settleCreditReservationResponse)
      })
  })
}

/**
 * Release a credit reservation
 *
 * POST /credit-reservations/{reservationId}/release
 */
export function releaseCreditReservation(
  client: Client,
  req: ReleaseCreditReservationRequest,
  options?: RequestOptions,
): Promise<Result<ReleaseCreditReservationResponse>> {
  return request(() => {
    const pathParamsInput = {
      reservationId: req.reservationId,
    }
    const pathParams = client._options.validate
      ? toPathWire(pathParamsInput, schemas.releaseCreditReservationPathParams)
      : pathParamsInput
    if (client._options.validate) {
      assertValid(schemas.releaseCreditReservationPathParamsWire, pathParams)
    }
    const path = `credit-reservations/${(() => { if (pathParams.reservationId === undefined) { throw new Error('missing path parameter: reservationId') } return encodeURIComponent(String(pathParams.reservationId)) })()}/release`
    const body = toWire(req.body, schemas.releaseCreditReservationBody)
    if (client._options.validate) {
      assertValid(schemas.releaseCreditReservationBodyWire, body)
    }
    return http(client)
      .post(path, { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.releaseCreditReservationResponseWire, data)
        }
        return fromWire(data, schemas.releaseCreditReservationResponse)
      })
  })
}

/**
 * Mark a credit reservation as unknown
 *
 * POST /credit-reservations/{reservationId}/unknown
 */
export function markCreditReservationUnknown(
  client: Client,
  req: MarkCreditReservationUnknownRequest,
  options?: RequestOptions,
): Promise<Result<MarkCreditReservationUnknownResponse>> {
  return request(() => {
    const pathParamsInput = {
      reservationId: req.reservationId,
    }
    const pathParams = client._options.validate
      ? toPathWire(pathParamsInput, schemas.markCreditReservationUnknownPathParams)
      : pathParamsInput
    if (client._options.validate) {
      assertValid(schemas.markCreditReservationUnknownPathParamsWire, pathParams)
    }
    const path = `credit-reservations/${(() => { if (pathParams.reservationId === undefined) { throw new Error('missing path parameter: reservationId') } return encodeURIComponent(String(pathParams.reservationId)) })()}/unknown`
    const body = toWire(req.body, schemas.markCreditReservationUnknownBody)
    if (client._options.validate) {
      assertValid(schemas.markCreditReservationUnknownBodyWire, body)
    }
    return http(client)
      .post(path, { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.markCreditReservationUnknownResponseWire, data)
        }
        return fromWire(data, schemas.markCreditReservationUnknownResponse)
      })
  })
}

/**
 * Create and settle a direct credit charge
 *
 * POST /credit-charges
 */
export function createCreditCharge(
  client: Client,
  req: CreateCreditChargeRequest,
  options?: RequestOptions,
): Promise<Result<CreateCreditChargeResponse>> {
  return request(() => {
    const body = toWire(req, schemas.createCreditChargeBody)
    if (client._options.validate) {
      assertValid(schemas.createCreditChargeBodyWire, body)
    }
    return http(client)
      .post('credit-charges', { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.createCreditChargeResponseWire, data)
        }
        return fromWire(data, schemas.createCreditChargeResponse)
      })
  })
}

/**
 * Reverse a direct credit charge
 *
 * POST /credit-charges/{chargeId}/reverse
 */
export function reverseCreditCharge(
  client: Client,
  req: ReverseCreditChargeRequest,
  options?: RequestOptions,
): Promise<Result<ReverseCreditChargeResponse>> {
  return request(() => {
    const pathParamsInput = {
      chargeId: req.chargeId,
    }
    const pathParams = client._options.validate
      ? toPathWire(pathParamsInput, schemas.reverseCreditChargePathParams)
      : pathParamsInput
    if (client._options.validate) {
      assertValid(schemas.reverseCreditChargePathParamsWire, pathParams)
    }
    const path = `credit-charges/${(() => { if (pathParams.chargeId === undefined) { throw new Error('missing path parameter: chargeId') } return encodeURIComponent(String(pathParams.chargeId)) })()}/reverse`
    const body = toWire(req.body, schemas.reverseCreditChargeBody)
    if (client._options.validate) {
      assertValid(schemas.reverseCreditChargeBodyWire, body)
    }
    return http(client)
      .post(path, { ...options, json: body })
      .json()
      .then((data) => {
        if (client._options.validate) {
          assertValid(schemas.reverseCreditChargeResponseWire, data)
        }
        return fromWire(data, schemas.reverseCreditChargeResponse)
      })
  })
}
