// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/commerceorder"
)

// CommerceOrder is the model entity for the CommerceOrder schema.
type CommerceOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind commerceorder.Kind `json:"kind,omitempty"`
	// Status holds the value of the "status" field.
	Status commerceorder.Status `json:"status,omitempty"`
	// TotalCents holds the value of the "total_cents" field.
	TotalCents int64 `json:"total_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommerceOrderQuery when eager-loading is set.
	Edges        CommerceOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CommerceOrderEdges holds the relations/edges for other nodes in the graph.
type CommerceOrderEdges struct {
	// Lines holds the value of the lines edge.
	Lines []*CommerceOrderLine `json:"lines,omitempty"`
	// PaymentAttempts holds the value of the payment_attempts edge.
	PaymentAttempts []*PaymentAttempt `json:"payment_attempts,omitempty"`
	// Fulfillments holds the value of the fulfillments edge.
	Fulfillments []*Fulfillment `json:"fulfillments,omitempty"`
	// RefundRequests holds the value of the refund_requests edge.
	RefundRequests []*RefundRequest `json:"refund_requests,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// LinesOrErr returns the Lines value or an error if the edge
// was not loaded in eager-loading.
func (e CommerceOrderEdges) LinesOrErr() ([]*CommerceOrderLine, error) {
	if e.loadedTypes[0] {
		return e.Lines, nil
	}
	return nil, &NotLoadedError{edge: "lines"}
}

// PaymentAttemptsOrErr returns the PaymentAttempts value or an error if the edge
// was not loaded in eager-loading.
func (e CommerceOrderEdges) PaymentAttemptsOrErr() ([]*PaymentAttempt, error) {
	if e.loadedTypes[1] {
		return e.PaymentAttempts, nil
	}
	return nil, &NotLoadedError{edge: "payment_attempts"}
}

// FulfillmentsOrErr returns the Fulfillments value or an error if the edge
// was not loaded in eager-loading.
func (e CommerceOrderEdges) FulfillmentsOrErr() ([]*Fulfillment, error) {
	if e.loadedTypes[2] {
		return e.Fulfillments, nil
	}
	return nil, &NotLoadedError{edge: "fulfillments"}
}

// RefundRequestsOrErr returns the RefundRequests value or an error if the edge
// was not loaded in eager-loading.
func (e CommerceOrderEdges) RefundRequestsOrErr() ([]*RefundRequest, error) {
	if e.loadedTypes[3] {
		return e.RefundRequests, nil
	}
	return nil, &NotLoadedError{edge: "refund_requests"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommerceOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commerceorder.FieldTotalCents:
			values[i] = new(sql.NullInt64)
		case commerceorder.FieldID, commerceorder.FieldNamespace, commerceorder.FieldPublicID, commerceorder.FieldCustomerID, commerceorder.FieldKind, commerceorder.FieldStatus, commerceorder.FieldCurrency, commerceorder.FieldIdempotencyKey, commerceorder.FieldDescription:
			values[i] = new(sql.NullString)
		case commerceorder.FieldCreatedAt, commerceorder.FieldUpdatedAt, commerceorder.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommerceOrder fields.
func (_m *CommerceOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commerceorder.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case commerceorder.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case commerceorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case commerceorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case commerceorder.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case commerceorder.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case commerceorder.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = value.String
			}
		case commerceorder.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = commerceorder.Kind(value.String)
			}
		case commerceorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = commerceorder.Status(value.String)
			}
		case commerceorder.FieldTotalCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cents", values[i])
			} else if value.Valid {
				_m.TotalCents = value.Int64
			}
		case commerceorder.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case commerceorder.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case commerceorder.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommerceOrder.
// This includes values selected through modifiers, order, etc.
func (_m *CommerceOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLines queries the "lines" edge of the CommerceOrder entity.
func (_m *CommerceOrder) QueryLines() *CommerceOrderLineQuery {
	return NewCommerceOrderClient(_m.config).QueryLines(_m)
}

// QueryPaymentAttempts queries the "payment_attempts" edge of the CommerceOrder entity.
func (_m *CommerceOrder) QueryPaymentAttempts() *PaymentAttemptQuery {
	return NewCommerceOrderClient(_m.config).QueryPaymentAttempts(_m)
}

// QueryFulfillments queries the "fulfillments" edge of the CommerceOrder entity.
func (_m *CommerceOrder) QueryFulfillments() *FulfillmentQuery {
	return NewCommerceOrderClient(_m.config).QueryFulfillments(_m)
}

// QueryRefundRequests queries the "refund_requests" edge of the CommerceOrder entity.
func (_m *CommerceOrder) QueryRefundRequests() *RefundRequestQuery {
	return NewCommerceOrderClient(_m.config).QueryRefundRequests(_m)
}

// Update returns a builder for updating this CommerceOrder.
// Note that you need to call CommerceOrder.Unwrap() before calling this method if this CommerceOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CommerceOrder) Update() *CommerceOrderUpdateOne {
	return NewCommerceOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CommerceOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CommerceOrder) Unwrap() *CommerceOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: CommerceOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CommerceOrder) String() string {
	var builder strings.Builder
	builder.WriteString("CommerceOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(_m.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("total_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCents))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CommerceOrders is a parsable slice of CommerceOrder.
type CommerceOrders []*CommerceOrder
