// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/currencies"
	"github.com/openmeterio/openmeter/openmeter/ent/db/creditreservation"
)

// CreditReservationCreate is the builder for creating a CreditReservation entity.
type CreditReservationCreate struct {
	config
	mutation *CreditReservationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNamespace sets the "namespace" field.
func (_c *CreditReservationCreate) SetNamespace(v string) *CreditReservationCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreditReservationCreate) SetCreatedAt(v time.Time) *CreditReservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableCreatedAt(v *time.Time) *CreditReservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CreditReservationCreate) SetUpdatedAt(v time.Time) *CreditReservationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableUpdatedAt(v *time.Time) *CreditReservationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CreditReservationCreate) SetDeletedAt(v time.Time) *CreditReservationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableDeletedAt(v *time.Time) *CreditReservationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *CreditReservationCreate) SetCustomerID(v string) *CreditReservationCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *CreditReservationCreate) SetSubjectID(v string) *CreditReservationCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetClientCallID sets the "client_call_id" field.
func (_c *CreditReservationCreate) SetClientCallID(v string) *CreditReservationCreate {
	_c.mutation.SetClientCallID(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *CreditReservationCreate) SetOperation(v string) *CreditReservationCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *CreditReservationCreate) SetIdempotencyKey(v string) *CreditReservationCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetPayloadHash sets the "payload_hash" field.
func (_c *CreditReservationCreate) SetPayloadHash(v string) *CreditReservationCreate {
	_c.mutation.SetPayloadHash(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CreditReservationCreate) SetCurrency(v currencies.CurrencyReference) *CreditReservationCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetCustomCurrencyID sets the "custom_currency_id" field.
func (_c *CreditReservationCreate) SetCustomCurrencyID(v string) *CreditReservationCreate {
	_c.mutation.SetCustomCurrencyID(v)
	return _c
}

// SetNillableCustomCurrencyID sets the "custom_currency_id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableCustomCurrencyID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetCustomCurrencyID(*v)
	}
	return _c
}

// SetEstimatedLines sets the "estimated_lines" field.
func (_c *CreditReservationCreate) SetEstimatedLines(v []json.RawMessage) *CreditReservationCreate {
	_c.mutation.SetEstimatedLines(v)
	return _c
}

// SetRatedLines sets the "rated_lines" field.
func (_c *CreditReservationCreate) SetRatedLines(v []json.RawMessage) *CreditReservationCreate {
	_c.mutation.SetRatedLines(v)
	return _c
}

// SetActualLines sets the "actual_lines" field.
func (_c *CreditReservationCreate) SetActualLines(v []json.RawMessage) *CreditReservationCreate {
	_c.mutation.SetActualLines(v)
	return _c
}

// SetCeilingCredits sets the "ceiling_credits" field.
func (_c *CreditReservationCreate) SetCeilingCredits(v int64) *CreditReservationCreate {
	_c.mutation.SetCeilingCredits(v)
	return _c
}

// SetNillableCeilingCredits sets the "ceiling_credits" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableCeilingCredits(v *int64) *CreditReservationCreate {
	if v != nil {
		_c.SetCeilingCredits(*v)
	}
	return _c
}

// SetPrepaidHold sets the "prepaid_hold" field.
func (_c *CreditReservationCreate) SetPrepaidHold(v int64) *CreditReservationCreate {
	_c.mutation.SetPrepaidHold(v)
	return _c
}

// SetNillablePrepaidHold sets the "prepaid_hold" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillablePrepaidHold(v *int64) *CreditReservationCreate {
	if v != nil {
		_c.SetPrepaidHold(*v)
	}
	return _c
}

// SetEnterpriseHold sets the "enterprise_hold" field.
func (_c *CreditReservationCreate) SetEnterpriseHold(v int64) *CreditReservationCreate {
	_c.mutation.SetEnterpriseHold(v)
	return _c
}

// SetNillableEnterpriseHold sets the "enterprise_hold" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableEnterpriseHold(v *int64) *CreditReservationCreate {
	if v != nil {
		_c.SetEnterpriseHold(*v)
	}
	return _c
}

// SetSettledCredits sets the "settled_credits" field.
func (_c *CreditReservationCreate) SetSettledCredits(v int64) *CreditReservationCreate {
	_c.mutation.SetSettledCredits(v)
	return _c
}

// SetNillableSettledCredits sets the "settled_credits" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableSettledCredits(v *int64) *CreditReservationCreate {
	if v != nil {
		_c.SetSettledCredits(*v)
	}
	return _c
}

// SetSettlementIdempotencyKey sets the "settlement_idempotency_key" field.
func (_c *CreditReservationCreate) SetSettlementIdempotencyKey(v string) *CreditReservationCreate {
	_c.mutation.SetSettlementIdempotencyKey(v)
	return _c
}

// SetNillableSettlementIdempotencyKey sets the "settlement_idempotency_key" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableSettlementIdempotencyKey(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetSettlementIdempotencyKey(*v)
	}
	return _c
}

// SetSettlementPayloadHash sets the "settlement_payload_hash" field.
func (_c *CreditReservationCreate) SetSettlementPayloadHash(v string) *CreditReservationCreate {
	_c.mutation.SetSettlementPayloadHash(v)
	return _c
}

// SetNillableSettlementPayloadHash sets the "settlement_payload_hash" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableSettlementPayloadHash(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetSettlementPayloadHash(*v)
	}
	return _c
}

// SetRateVersion sets the "rate_version" field.
func (_c *CreditReservationCreate) SetRateVersion(v string) *CreditReservationCreate {
	_c.mutation.SetRateVersion(v)
	return _c
}

// SetNillableRateVersion sets the "rate_version" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableRateVersion(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetRateVersion(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *CreditReservationCreate) SetState(v string) *CreditReservationCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *CreditReservationCreate) SetProvider(v string) *CreditReservationCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableProvider(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *CreditReservationCreate) SetModel(v string) *CreditReservationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableModel(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *CreditReservationCreate) SetRequestID(v string) *CreditReservationCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableRequestID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetAuthorizationExpiresAt sets the "authorization_expires_at" field.
func (_c *CreditReservationCreate) SetAuthorizationExpiresAt(v time.Time) *CreditReservationCreate {
	_c.mutation.SetAuthorizationExpiresAt(v)
	return _c
}

// SetNillableAuthorizationExpiresAt sets the "authorization_expires_at" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableAuthorizationExpiresAt(v *time.Time) *CreditReservationCreate {
	if v != nil {
		_c.SetAuthorizationExpiresAt(*v)
	}
	return _c
}

// SetExecutionDeadline sets the "execution_deadline" field.
func (_c *CreditReservationCreate) SetExecutionDeadline(v time.Time) *CreditReservationCreate {
	_c.mutation.SetExecutionDeadline(v)
	return _c
}

// SetNillableExecutionDeadline sets the "execution_deadline" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableExecutionDeadline(v *time.Time) *CreditReservationCreate {
	if v != nil {
		_c.SetExecutionDeadline(*v)
	}
	return _c
}

// SetHoldLedgerGroupID sets the "hold_ledger_group_id" field.
func (_c *CreditReservationCreate) SetHoldLedgerGroupID(v string) *CreditReservationCreate {
	_c.mutation.SetHoldLedgerGroupID(v)
	return _c
}

// SetNillableHoldLedgerGroupID sets the "hold_ledger_group_id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableHoldLedgerGroupID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetHoldLedgerGroupID(*v)
	}
	return _c
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (_c *CreditReservationCreate) SetSettlementLedgerGroupID(v string) *CreditReservationCreate {
	_c.mutation.SetSettlementLedgerGroupID(v)
	return _c
}

// SetNillableSettlementLedgerGroupID sets the "settlement_ledger_group_id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableSettlementLedgerGroupID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetSettlementLedgerGroupID(*v)
	}
	return _c
}

// SetReleaseLedgerGroupID sets the "release_ledger_group_id" field.
func (_c *CreditReservationCreate) SetReleaseLedgerGroupID(v string) *CreditReservationCreate {
	_c.mutation.SetReleaseLedgerGroupID(v)
	return _c
}

// SetNillableReleaseLedgerGroupID sets the "release_ledger_group_id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableReleaseLedgerGroupID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetReleaseLedgerGroupID(*v)
	}
	return _c
}

// SetUsageEventID sets the "usage_event_id" field.
func (_c *CreditReservationCreate) SetUsageEventID(v string) *CreditReservationCreate {
	_c.mutation.SetUsageEventID(v)
	return _c
}

// SetNillableUsageEventID sets the "usage_event_id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableUsageEventID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetUsageEventID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CreditReservationCreate) SetID(v string) *CreditReservationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CreditReservationCreate) SetNillableID(v *string) *CreditReservationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CreditReservationMutation object of the builder.
func (_c *CreditReservationCreate) Mutation() *CreditReservationMutation {
	return _c.mutation
}

// Save creates the CreditReservation in the database.
func (_c *CreditReservationCreate) Save(ctx context.Context) (*CreditReservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreditReservationCreate) SaveX(ctx context.Context) *CreditReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreditReservationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creditreservation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := creditreservation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CeilingCredits(); !ok {
		v := creditreservation.DefaultCeilingCredits
		_c.mutation.SetCeilingCredits(v)
	}
	if _, ok := _c.mutation.PrepaidHold(); !ok {
		v := creditreservation.DefaultPrepaidHold
		_c.mutation.SetPrepaidHold(v)
	}
	if _, ok := _c.mutation.EnterpriseHold(); !ok {
		v := creditreservation.DefaultEnterpriseHold
		_c.mutation.SetEnterpriseHold(v)
	}
	if _, ok := _c.mutation.SettledCredits(); !ok {
		v := creditreservation.DefaultSettledCredits
		_c.mutation.SetSettledCredits(v)
	}
	if _, ok := _c.mutation.SettlementIdempotencyKey(); !ok {
		v := creditreservation.DefaultSettlementIdempotencyKey
		_c.mutation.SetSettlementIdempotencyKey(v)
	}
	if _, ok := _c.mutation.SettlementPayloadHash(); !ok {
		v := creditreservation.DefaultSettlementPayloadHash
		_c.mutation.SetSettlementPayloadHash(v)
	}
	if _, ok := _c.mutation.RateVersion(); !ok {
		v := creditreservation.DefaultRateVersion
		_c.mutation.SetRateVersion(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := creditreservation.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := creditreservation.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := creditreservation.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.HoldLedgerGroupID(); !ok {
		v := creditreservation.DefaultHoldLedgerGroupID
		_c.mutation.SetHoldLedgerGroupID(v)
	}
	if _, ok := _c.mutation.SettlementLedgerGroupID(); !ok {
		v := creditreservation.DefaultSettlementLedgerGroupID
		_c.mutation.SetSettlementLedgerGroupID(v)
	}
	if _, ok := _c.mutation.ReleaseLedgerGroupID(); !ok {
		v := creditreservation.DefaultReleaseLedgerGroupID
		_c.mutation.SetReleaseLedgerGroupID(v)
	}
	if _, ok := _c.mutation.UsageEventID(); !ok {
		v := creditreservation.DefaultUsageEventID
		_c.mutation.SetUsageEventID(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := creditreservation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreditReservationCreate) check() error {
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`db: missing required field "CreditReservation.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := creditreservation.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`db: validator failed for field "CreditReservation.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "CreditReservation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "CreditReservation.updated_at"`)}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`db: missing required field "CreditReservation.customer_id"`)}
	}
	if v, ok := _c.mutation.CustomerID(); ok {
		if err := creditreservation.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`db: validator failed for field "CreditReservation.customer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`db: missing required field "CreditReservation.subject_id"`)}
	}
	if v, ok := _c.mutation.SubjectID(); ok {
		if err := creditreservation.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`db: validator failed for field "CreditReservation.subject_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientCallID(); !ok {
		return &ValidationError{Name: "client_call_id", err: errors.New(`db: missing required field "CreditReservation.client_call_id"`)}
	}
	if v, ok := _c.mutation.ClientCallID(); ok {
		if err := creditreservation.ClientCallIDValidator(v); err != nil {
			return &ValidationError{Name: "client_call_id", err: fmt.Errorf(`db: validator failed for field "CreditReservation.client_call_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`db: missing required field "CreditReservation.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := creditreservation.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`db: validator failed for field "CreditReservation.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`db: missing required field "CreditReservation.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := creditreservation.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`db: validator failed for field "CreditReservation.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayloadHash(); !ok {
		return &ValidationError{Name: "payload_hash", err: errors.New(`db: missing required field "CreditReservation.payload_hash"`)}
	}
	if v, ok := _c.mutation.PayloadHash(); ok {
		if err := creditreservation.PayloadHashValidator(v); err != nil {
			return &ValidationError{Name: "payload_hash", err: fmt.Errorf(`db: validator failed for field "CreditReservation.payload_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`db: missing required field "CreditReservation.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`db: validator failed for field "CreditReservation.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EstimatedLines(); !ok {
		return &ValidationError{Name: "estimated_lines", err: errors.New(`db: missing required field "CreditReservation.estimated_lines"`)}
	}
	if _, ok := _c.mutation.RatedLines(); !ok {
		return &ValidationError{Name: "rated_lines", err: errors.New(`db: missing required field "CreditReservation.rated_lines"`)}
	}
	if _, ok := _c.mutation.CeilingCredits(); !ok {
		return &ValidationError{Name: "ceiling_credits", err: errors.New(`db: missing required field "CreditReservation.ceiling_credits"`)}
	}
	if _, ok := _c.mutation.PrepaidHold(); !ok {
		return &ValidationError{Name: "prepaid_hold", err: errors.New(`db: missing required field "CreditReservation.prepaid_hold"`)}
	}
	if _, ok := _c.mutation.EnterpriseHold(); !ok {
		return &ValidationError{Name: "enterprise_hold", err: errors.New(`db: missing required field "CreditReservation.enterprise_hold"`)}
	}
	if _, ok := _c.mutation.SettledCredits(); !ok {
		return &ValidationError{Name: "settled_credits", err: errors.New(`db: missing required field "CreditReservation.settled_credits"`)}
	}
	if _, ok := _c.mutation.SettlementIdempotencyKey(); !ok {
		return &ValidationError{Name: "settlement_idempotency_key", err: errors.New(`db: missing required field "CreditReservation.settlement_idempotency_key"`)}
	}
	if _, ok := _c.mutation.SettlementPayloadHash(); !ok {
		return &ValidationError{Name: "settlement_payload_hash", err: errors.New(`db: missing required field "CreditReservation.settlement_payload_hash"`)}
	}
	if _, ok := _c.mutation.RateVersion(); !ok {
		return &ValidationError{Name: "rate_version", err: errors.New(`db: missing required field "CreditReservation.rate_version"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`db: missing required field "CreditReservation.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := creditreservation.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`db: validator failed for field "CreditReservation.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`db: missing required field "CreditReservation.provider"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`db: missing required field "CreditReservation.model"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`db: missing required field "CreditReservation.request_id"`)}
	}
	if _, ok := _c.mutation.HoldLedgerGroupID(); !ok {
		return &ValidationError{Name: "hold_ledger_group_id", err: errors.New(`db: missing required field "CreditReservation.hold_ledger_group_id"`)}
	}
	if _, ok := _c.mutation.SettlementLedgerGroupID(); !ok {
		return &ValidationError{Name: "settlement_ledger_group_id", err: errors.New(`db: missing required field "CreditReservation.settlement_ledger_group_id"`)}
	}
	if _, ok := _c.mutation.ReleaseLedgerGroupID(); !ok {
		return &ValidationError{Name: "release_ledger_group_id", err: errors.New(`db: missing required field "CreditReservation.release_ledger_group_id"`)}
	}
	if _, ok := _c.mutation.UsageEventID(); !ok {
		return &ValidationError{Name: "usage_event_id", err: errors.New(`db: missing required field "CreditReservation.usage_event_id"`)}
	}
	return nil
}

func (_c *CreditReservationCreate) sqlSave(ctx context.Context) (*CreditReservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CreditReservation.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreditReservationCreate) createSpec() (*CreditReservation, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditReservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creditreservation.Table, sqlgraph.NewFieldSpec(creditreservation.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(creditreservation.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creditreservation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(creditreservation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(creditreservation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(creditreservation.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(creditreservation.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.ClientCallID(); ok {
		_spec.SetField(creditreservation.FieldClientCallID, field.TypeString, value)
		_node.ClientCallID = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(creditreservation.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(creditreservation.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.PayloadHash(); ok {
		_spec.SetField(creditreservation.FieldPayloadHash, field.TypeString, value)
		_node.PayloadHash = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(creditreservation.FieldCurrency, field.TypeJSON, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.CustomCurrencyID(); ok {
		_spec.SetField(creditreservation.FieldCustomCurrencyID, field.TypeString, value)
		_node.CustomCurrencyID = &value
	}
	if value, ok := _c.mutation.EstimatedLines(); ok {
		_spec.SetField(creditreservation.FieldEstimatedLines, field.TypeJSON, value)
		_node.EstimatedLines = value
	}
	if value, ok := _c.mutation.RatedLines(); ok {
		_spec.SetField(creditreservation.FieldRatedLines, field.TypeJSON, value)
		_node.RatedLines = value
	}
	if value, ok := _c.mutation.ActualLines(); ok {
		_spec.SetField(creditreservation.FieldActualLines, field.TypeJSON, value)
		_node.ActualLines = value
	}
	if value, ok := _c.mutation.CeilingCredits(); ok {
		_spec.SetField(creditreservation.FieldCeilingCredits, field.TypeInt64, value)
		_node.CeilingCredits = value
	}
	if value, ok := _c.mutation.PrepaidHold(); ok {
		_spec.SetField(creditreservation.FieldPrepaidHold, field.TypeInt64, value)
		_node.PrepaidHold = value
	}
	if value, ok := _c.mutation.EnterpriseHold(); ok {
		_spec.SetField(creditreservation.FieldEnterpriseHold, field.TypeInt64, value)
		_node.EnterpriseHold = value
	}
	if value, ok := _c.mutation.SettledCredits(); ok {
		_spec.SetField(creditreservation.FieldSettledCredits, field.TypeInt64, value)
		_node.SettledCredits = value
	}
	if value, ok := _c.mutation.SettlementIdempotencyKey(); ok {
		_spec.SetField(creditreservation.FieldSettlementIdempotencyKey, field.TypeString, value)
		_node.SettlementIdempotencyKey = value
	}
	if value, ok := _c.mutation.SettlementPayloadHash(); ok {
		_spec.SetField(creditreservation.FieldSettlementPayloadHash, field.TypeString, value)
		_node.SettlementPayloadHash = value
	}
	if value, ok := _c.mutation.RateVersion(); ok {
		_spec.SetField(creditreservation.FieldRateVersion, field.TypeString, value)
		_node.RateVersion = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(creditreservation.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(creditreservation.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(creditreservation.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(creditreservation.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.AuthorizationExpiresAt(); ok {
		_spec.SetField(creditreservation.FieldAuthorizationExpiresAt, field.TypeTime, value)
		_node.AuthorizationExpiresAt = &value
	}
	if value, ok := _c.mutation.ExecutionDeadline(); ok {
		_spec.SetField(creditreservation.FieldExecutionDeadline, field.TypeTime, value)
		_node.ExecutionDeadline = &value
	}
	if value, ok := _c.mutation.HoldLedgerGroupID(); ok {
		_spec.SetField(creditreservation.FieldHoldLedgerGroupID, field.TypeString, value)
		_node.HoldLedgerGroupID = value
	}
	if value, ok := _c.mutation.SettlementLedgerGroupID(); ok {
		_spec.SetField(creditreservation.FieldSettlementLedgerGroupID, field.TypeString, value)
		_node.SettlementLedgerGroupID = value
	}
	if value, ok := _c.mutation.ReleaseLedgerGroupID(); ok {
		_spec.SetField(creditreservation.FieldReleaseLedgerGroupID, field.TypeString, value)
		_node.ReleaseLedgerGroupID = value
	}
	if value, ok := _c.mutation.UsageEventID(); ok {
		_spec.SetField(creditreservation.FieldUsageEventID, field.TypeString, value)
		_node.UsageEventID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditReservation.Create().
//		SetNamespace(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditReservationUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditReservationCreate) OnConflict(opts ...sql.ConflictOption) *CreditReservationUpsertOne {
	_c.conflict = opts
	return &CreditReservationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditReservationCreate) OnConflictColumns(columns ...string) *CreditReservationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditReservationUpsertOne{
		create: _c,
	}
}

type (
	// CreditReservationUpsertOne is the builder for "upsert"-ing
	//  one CreditReservation node.
	CreditReservationUpsertOne struct {
		create *CreditReservationCreate
	}

	// CreditReservationUpsert is the "OnConflict" setter.
	CreditReservationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CreditReservationUpsert) SetUpdatedAt(v time.Time) *CreditReservationUpsert {
	u.Set(creditreservation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateUpdatedAt() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CreditReservationUpsert) SetDeletedAt(v time.Time) *CreditReservationUpsert {
	u.Set(creditreservation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateDeletedAt() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CreditReservationUpsert) ClearDeletedAt() *CreditReservationUpsert {
	u.SetNull(creditreservation.FieldDeletedAt)
	return u
}

// SetEstimatedLines sets the "estimated_lines" field.
func (u *CreditReservationUpsert) SetEstimatedLines(v []json.RawMessage) *CreditReservationUpsert {
	u.Set(creditreservation.FieldEstimatedLines, v)
	return u
}

// UpdateEstimatedLines sets the "estimated_lines" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateEstimatedLines() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldEstimatedLines)
	return u
}

// SetRatedLines sets the "rated_lines" field.
func (u *CreditReservationUpsert) SetRatedLines(v []json.RawMessage) *CreditReservationUpsert {
	u.Set(creditreservation.FieldRatedLines, v)
	return u
}

// UpdateRatedLines sets the "rated_lines" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateRatedLines() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldRatedLines)
	return u
}

// SetActualLines sets the "actual_lines" field.
func (u *CreditReservationUpsert) SetActualLines(v []json.RawMessage) *CreditReservationUpsert {
	u.Set(creditreservation.FieldActualLines, v)
	return u
}

// UpdateActualLines sets the "actual_lines" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateActualLines() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldActualLines)
	return u
}

// ClearActualLines clears the value of the "actual_lines" field.
func (u *CreditReservationUpsert) ClearActualLines() *CreditReservationUpsert {
	u.SetNull(creditreservation.FieldActualLines)
	return u
}

// SetCeilingCredits sets the "ceiling_credits" field.
func (u *CreditReservationUpsert) SetCeilingCredits(v int64) *CreditReservationUpsert {
	u.Set(creditreservation.FieldCeilingCredits, v)
	return u
}

// UpdateCeilingCredits sets the "ceiling_credits" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateCeilingCredits() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldCeilingCredits)
	return u
}

// AddCeilingCredits adds v to the "ceiling_credits" field.
func (u *CreditReservationUpsert) AddCeilingCredits(v int64) *CreditReservationUpsert {
	u.Add(creditreservation.FieldCeilingCredits, v)
	return u
}

// SetPrepaidHold sets the "prepaid_hold" field.
func (u *CreditReservationUpsert) SetPrepaidHold(v int64) *CreditReservationUpsert {
	u.Set(creditreservation.FieldPrepaidHold, v)
	return u
}

// UpdatePrepaidHold sets the "prepaid_hold" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdatePrepaidHold() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldPrepaidHold)
	return u
}

// AddPrepaidHold adds v to the "prepaid_hold" field.
func (u *CreditReservationUpsert) AddPrepaidHold(v int64) *CreditReservationUpsert {
	u.Add(creditreservation.FieldPrepaidHold, v)
	return u
}

// SetEnterpriseHold sets the "enterprise_hold" field.
func (u *CreditReservationUpsert) SetEnterpriseHold(v int64) *CreditReservationUpsert {
	u.Set(creditreservation.FieldEnterpriseHold, v)
	return u
}

// UpdateEnterpriseHold sets the "enterprise_hold" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateEnterpriseHold() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldEnterpriseHold)
	return u
}

// AddEnterpriseHold adds v to the "enterprise_hold" field.
func (u *CreditReservationUpsert) AddEnterpriseHold(v int64) *CreditReservationUpsert {
	u.Add(creditreservation.FieldEnterpriseHold, v)
	return u
}

// SetSettledCredits sets the "settled_credits" field.
func (u *CreditReservationUpsert) SetSettledCredits(v int64) *CreditReservationUpsert {
	u.Set(creditreservation.FieldSettledCredits, v)
	return u
}

// UpdateSettledCredits sets the "settled_credits" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateSettledCredits() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldSettledCredits)
	return u
}

// AddSettledCredits adds v to the "settled_credits" field.
func (u *CreditReservationUpsert) AddSettledCredits(v int64) *CreditReservationUpsert {
	u.Add(creditreservation.FieldSettledCredits, v)
	return u
}

// SetSettlementIdempotencyKey sets the "settlement_idempotency_key" field.
func (u *CreditReservationUpsert) SetSettlementIdempotencyKey(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldSettlementIdempotencyKey, v)
	return u
}

// UpdateSettlementIdempotencyKey sets the "settlement_idempotency_key" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateSettlementIdempotencyKey() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldSettlementIdempotencyKey)
	return u
}

// SetSettlementPayloadHash sets the "settlement_payload_hash" field.
func (u *CreditReservationUpsert) SetSettlementPayloadHash(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldSettlementPayloadHash, v)
	return u
}

// UpdateSettlementPayloadHash sets the "settlement_payload_hash" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateSettlementPayloadHash() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldSettlementPayloadHash)
	return u
}

// SetRateVersion sets the "rate_version" field.
func (u *CreditReservationUpsert) SetRateVersion(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldRateVersion, v)
	return u
}

// UpdateRateVersion sets the "rate_version" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateRateVersion() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldRateVersion)
	return u
}

// SetState sets the "state" field.
func (u *CreditReservationUpsert) SetState(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateState() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldState)
	return u
}

// SetProvider sets the "provider" field.
func (u *CreditReservationUpsert) SetProvider(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateProvider() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *CreditReservationUpsert) SetModel(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateModel() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldModel)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *CreditReservationUpsert) SetRequestID(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateRequestID() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldRequestID)
	return u
}

// SetAuthorizationExpiresAt sets the "authorization_expires_at" field.
func (u *CreditReservationUpsert) SetAuthorizationExpiresAt(v time.Time) *CreditReservationUpsert {
	u.Set(creditreservation.FieldAuthorizationExpiresAt, v)
	return u
}

// UpdateAuthorizationExpiresAt sets the "authorization_expires_at" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateAuthorizationExpiresAt() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldAuthorizationExpiresAt)
	return u
}

// ClearAuthorizationExpiresAt clears the value of the "authorization_expires_at" field.
func (u *CreditReservationUpsert) ClearAuthorizationExpiresAt() *CreditReservationUpsert {
	u.SetNull(creditreservation.FieldAuthorizationExpiresAt)
	return u
}

// SetExecutionDeadline sets the "execution_deadline" field.
func (u *CreditReservationUpsert) SetExecutionDeadline(v time.Time) *CreditReservationUpsert {
	u.Set(creditreservation.FieldExecutionDeadline, v)
	return u
}

// UpdateExecutionDeadline sets the "execution_deadline" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateExecutionDeadline() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldExecutionDeadline)
	return u
}

// ClearExecutionDeadline clears the value of the "execution_deadline" field.
func (u *CreditReservationUpsert) ClearExecutionDeadline() *CreditReservationUpsert {
	u.SetNull(creditreservation.FieldExecutionDeadline)
	return u
}

// SetHoldLedgerGroupID sets the "hold_ledger_group_id" field.
func (u *CreditReservationUpsert) SetHoldLedgerGroupID(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldHoldLedgerGroupID, v)
	return u
}

// UpdateHoldLedgerGroupID sets the "hold_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateHoldLedgerGroupID() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldHoldLedgerGroupID)
	return u
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (u *CreditReservationUpsert) SetSettlementLedgerGroupID(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldSettlementLedgerGroupID, v)
	return u
}

// UpdateSettlementLedgerGroupID sets the "settlement_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateSettlementLedgerGroupID() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldSettlementLedgerGroupID)
	return u
}

// SetReleaseLedgerGroupID sets the "release_ledger_group_id" field.
func (u *CreditReservationUpsert) SetReleaseLedgerGroupID(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldReleaseLedgerGroupID, v)
	return u
}

// UpdateReleaseLedgerGroupID sets the "release_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateReleaseLedgerGroupID() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldReleaseLedgerGroupID)
	return u
}

// SetUsageEventID sets the "usage_event_id" field.
func (u *CreditReservationUpsert) SetUsageEventID(v string) *CreditReservationUpsert {
	u.Set(creditreservation.FieldUsageEventID, v)
	return u
}

// UpdateUsageEventID sets the "usage_event_id" field to the value that was provided on create.
func (u *CreditReservationUpsert) UpdateUsageEventID() *CreditReservationUpsert {
	u.SetExcluded(creditreservation.FieldUsageEventID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CreditReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(creditreservation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreditReservationUpsertOne) UpdateNewValues() *CreditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(creditreservation.FieldID)
		}
		if _, exists := u.create.mutation.Namespace(); exists {
			s.SetIgnore(creditreservation.FieldNamespace)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creditreservation.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.CustomerID(); exists {
			s.SetIgnore(creditreservation.FieldCustomerID)
		}
		if _, exists := u.create.mutation.SubjectID(); exists {
			s.SetIgnore(creditreservation.FieldSubjectID)
		}
		if _, exists := u.create.mutation.ClientCallID(); exists {
			s.SetIgnore(creditreservation.FieldClientCallID)
		}
		if _, exists := u.create.mutation.Operation(); exists {
			s.SetIgnore(creditreservation.FieldOperation)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(creditreservation.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.PayloadHash(); exists {
			s.SetIgnore(creditreservation.FieldPayloadHash)
		}
		if _, exists := u.create.mutation.Currency(); exists {
			s.SetIgnore(creditreservation.FieldCurrency)
		}
		if _, exists := u.create.mutation.CustomCurrencyID(); exists {
			s.SetIgnore(creditreservation.FieldCustomCurrencyID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditReservation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreditReservationUpsertOne) Ignore() *CreditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditReservationUpsertOne) DoNothing() *CreditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditReservationCreate.OnConflict
// documentation for more info.
func (u *CreditReservationUpsertOne) Update(set func(*CreditReservationUpsert)) *CreditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreditReservationUpsertOne) SetUpdatedAt(v time.Time) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateUpdatedAt() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CreditReservationUpsertOne) SetDeletedAt(v time.Time) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateDeletedAt() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CreditReservationUpsertOne) ClearDeletedAt() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEstimatedLines sets the "estimated_lines" field.
func (u *CreditReservationUpsertOne) SetEstimatedLines(v []json.RawMessage) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetEstimatedLines(v)
	})
}

// UpdateEstimatedLines sets the "estimated_lines" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateEstimatedLines() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateEstimatedLines()
	})
}

// SetRatedLines sets the "rated_lines" field.
func (u *CreditReservationUpsertOne) SetRatedLines(v []json.RawMessage) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetRatedLines(v)
	})
}

// UpdateRatedLines sets the "rated_lines" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateRatedLines() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateRatedLines()
	})
}

// SetActualLines sets the "actual_lines" field.
func (u *CreditReservationUpsertOne) SetActualLines(v []json.RawMessage) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetActualLines(v)
	})
}

// UpdateActualLines sets the "actual_lines" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateActualLines() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateActualLines()
	})
}

// ClearActualLines clears the value of the "actual_lines" field.
func (u *CreditReservationUpsertOne) ClearActualLines() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearActualLines()
	})
}

// SetCeilingCredits sets the "ceiling_credits" field.
func (u *CreditReservationUpsertOne) SetCeilingCredits(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetCeilingCredits(v)
	})
}

// AddCeilingCredits adds v to the "ceiling_credits" field.
func (u *CreditReservationUpsertOne) AddCeilingCredits(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddCeilingCredits(v)
	})
}

// UpdateCeilingCredits sets the "ceiling_credits" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateCeilingCredits() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateCeilingCredits()
	})
}

// SetPrepaidHold sets the "prepaid_hold" field.
func (u *CreditReservationUpsertOne) SetPrepaidHold(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetPrepaidHold(v)
	})
}

// AddPrepaidHold adds v to the "prepaid_hold" field.
func (u *CreditReservationUpsertOne) AddPrepaidHold(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddPrepaidHold(v)
	})
}

// UpdatePrepaidHold sets the "prepaid_hold" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdatePrepaidHold() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdatePrepaidHold()
	})
}

// SetEnterpriseHold sets the "enterprise_hold" field.
func (u *CreditReservationUpsertOne) SetEnterpriseHold(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetEnterpriseHold(v)
	})
}

// AddEnterpriseHold adds v to the "enterprise_hold" field.
func (u *CreditReservationUpsertOne) AddEnterpriseHold(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddEnterpriseHold(v)
	})
}

// UpdateEnterpriseHold sets the "enterprise_hold" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateEnterpriseHold() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateEnterpriseHold()
	})
}

// SetSettledCredits sets the "settled_credits" field.
func (u *CreditReservationUpsertOne) SetSettledCredits(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettledCredits(v)
	})
}

// AddSettledCredits adds v to the "settled_credits" field.
func (u *CreditReservationUpsertOne) AddSettledCredits(v int64) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddSettledCredits(v)
	})
}

// UpdateSettledCredits sets the "settled_credits" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateSettledCredits() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettledCredits()
	})
}

// SetSettlementIdempotencyKey sets the "settlement_idempotency_key" field.
func (u *CreditReservationUpsertOne) SetSettlementIdempotencyKey(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettlementIdempotencyKey(v)
	})
}

// UpdateSettlementIdempotencyKey sets the "settlement_idempotency_key" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateSettlementIdempotencyKey() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettlementIdempotencyKey()
	})
}

// SetSettlementPayloadHash sets the "settlement_payload_hash" field.
func (u *CreditReservationUpsertOne) SetSettlementPayloadHash(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettlementPayloadHash(v)
	})
}

// UpdateSettlementPayloadHash sets the "settlement_payload_hash" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateSettlementPayloadHash() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettlementPayloadHash()
	})
}

// SetRateVersion sets the "rate_version" field.
func (u *CreditReservationUpsertOne) SetRateVersion(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetRateVersion(v)
	})
}

// UpdateRateVersion sets the "rate_version" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateRateVersion() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateRateVersion()
	})
}

// SetState sets the "state" field.
func (u *CreditReservationUpsertOne) SetState(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateState() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateState()
	})
}

// SetProvider sets the "provider" field.
func (u *CreditReservationUpsertOne) SetProvider(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateProvider() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *CreditReservationUpsertOne) SetModel(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateModel() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateModel()
	})
}

// SetRequestID sets the "request_id" field.
func (u *CreditReservationUpsertOne) SetRequestID(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateRequestID() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateRequestID()
	})
}

// SetAuthorizationExpiresAt sets the "authorization_expires_at" field.
func (u *CreditReservationUpsertOne) SetAuthorizationExpiresAt(v time.Time) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetAuthorizationExpiresAt(v)
	})
}

// UpdateAuthorizationExpiresAt sets the "authorization_expires_at" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateAuthorizationExpiresAt() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateAuthorizationExpiresAt()
	})
}

// ClearAuthorizationExpiresAt clears the value of the "authorization_expires_at" field.
func (u *CreditReservationUpsertOne) ClearAuthorizationExpiresAt() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearAuthorizationExpiresAt()
	})
}

// SetExecutionDeadline sets the "execution_deadline" field.
func (u *CreditReservationUpsertOne) SetExecutionDeadline(v time.Time) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetExecutionDeadline(v)
	})
}

// UpdateExecutionDeadline sets the "execution_deadline" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateExecutionDeadline() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateExecutionDeadline()
	})
}

// ClearExecutionDeadline clears the value of the "execution_deadline" field.
func (u *CreditReservationUpsertOne) ClearExecutionDeadline() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearExecutionDeadline()
	})
}

// SetHoldLedgerGroupID sets the "hold_ledger_group_id" field.
func (u *CreditReservationUpsertOne) SetHoldLedgerGroupID(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetHoldLedgerGroupID(v)
	})
}

// UpdateHoldLedgerGroupID sets the "hold_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateHoldLedgerGroupID() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateHoldLedgerGroupID()
	})
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (u *CreditReservationUpsertOne) SetSettlementLedgerGroupID(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettlementLedgerGroupID(v)
	})
}

// UpdateSettlementLedgerGroupID sets the "settlement_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateSettlementLedgerGroupID() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettlementLedgerGroupID()
	})
}

// SetReleaseLedgerGroupID sets the "release_ledger_group_id" field.
func (u *CreditReservationUpsertOne) SetReleaseLedgerGroupID(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetReleaseLedgerGroupID(v)
	})
}

// UpdateReleaseLedgerGroupID sets the "release_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateReleaseLedgerGroupID() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateReleaseLedgerGroupID()
	})
}

// SetUsageEventID sets the "usage_event_id" field.
func (u *CreditReservationUpsertOne) SetUsageEventID(v string) *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetUsageEventID(v)
	})
}

// UpdateUsageEventID sets the "usage_event_id" field to the value that was provided on create.
func (u *CreditReservationUpsertOne) UpdateUsageEventID() *CreditReservationUpsertOne {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateUsageEventID()
	})
}

// Exec executes the query.
func (u *CreditReservationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for CreditReservationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditReservationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreditReservationUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: CreditReservationUpsertOne.ID is not supported by MySQL driver. Use CreditReservationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreditReservationUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreditReservationCreateBulk is the builder for creating many CreditReservation entities in bulk.
type CreditReservationCreateBulk struct {
	config
	err      error
	builders []*CreditReservationCreate
	conflict []sql.ConflictOption
}

// Save creates the CreditReservation entities in the database.
func (_c *CreditReservationCreateBulk) Save(ctx context.Context) ([]*CreditReservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreditReservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreditReservationCreateBulk) SaveX(ctx context.Context) []*CreditReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditReservation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditReservationUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditReservationCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreditReservationUpsertBulk {
	_c.conflict = opts
	return &CreditReservationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditReservationCreateBulk) OnConflictColumns(columns ...string) *CreditReservationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditReservationUpsertBulk{
		create: _c,
	}
}

// CreditReservationUpsertBulk is the builder for "upsert"-ing
// a bulk of CreditReservation nodes.
type CreditReservationUpsertBulk struct {
	create *CreditReservationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreditReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(creditreservation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreditReservationUpsertBulk) UpdateNewValues() *CreditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(creditreservation.FieldID)
			}
			if _, exists := b.mutation.Namespace(); exists {
				s.SetIgnore(creditreservation.FieldNamespace)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creditreservation.FieldCreatedAt)
			}
			if _, exists := b.mutation.CustomerID(); exists {
				s.SetIgnore(creditreservation.FieldCustomerID)
			}
			if _, exists := b.mutation.SubjectID(); exists {
				s.SetIgnore(creditreservation.FieldSubjectID)
			}
			if _, exists := b.mutation.ClientCallID(); exists {
				s.SetIgnore(creditreservation.FieldClientCallID)
			}
			if _, exists := b.mutation.Operation(); exists {
				s.SetIgnore(creditreservation.FieldOperation)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(creditreservation.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.PayloadHash(); exists {
				s.SetIgnore(creditreservation.FieldPayloadHash)
			}
			if _, exists := b.mutation.Currency(); exists {
				s.SetIgnore(creditreservation.FieldCurrency)
			}
			if _, exists := b.mutation.CustomCurrencyID(); exists {
				s.SetIgnore(creditreservation.FieldCustomCurrencyID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditReservation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreditReservationUpsertBulk) Ignore() *CreditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditReservationUpsertBulk) DoNothing() *CreditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditReservationCreateBulk.OnConflict
// documentation for more info.
func (u *CreditReservationUpsertBulk) Update(set func(*CreditReservationUpsert)) *CreditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreditReservationUpsertBulk) SetUpdatedAt(v time.Time) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateUpdatedAt() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CreditReservationUpsertBulk) SetDeletedAt(v time.Time) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateDeletedAt() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CreditReservationUpsertBulk) ClearDeletedAt() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEstimatedLines sets the "estimated_lines" field.
func (u *CreditReservationUpsertBulk) SetEstimatedLines(v []json.RawMessage) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetEstimatedLines(v)
	})
}

// UpdateEstimatedLines sets the "estimated_lines" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateEstimatedLines() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateEstimatedLines()
	})
}

// SetRatedLines sets the "rated_lines" field.
func (u *CreditReservationUpsertBulk) SetRatedLines(v []json.RawMessage) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetRatedLines(v)
	})
}

// UpdateRatedLines sets the "rated_lines" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateRatedLines() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateRatedLines()
	})
}

// SetActualLines sets the "actual_lines" field.
func (u *CreditReservationUpsertBulk) SetActualLines(v []json.RawMessage) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetActualLines(v)
	})
}

// UpdateActualLines sets the "actual_lines" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateActualLines() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateActualLines()
	})
}

// ClearActualLines clears the value of the "actual_lines" field.
func (u *CreditReservationUpsertBulk) ClearActualLines() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearActualLines()
	})
}

// SetCeilingCredits sets the "ceiling_credits" field.
func (u *CreditReservationUpsertBulk) SetCeilingCredits(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetCeilingCredits(v)
	})
}

// AddCeilingCredits adds v to the "ceiling_credits" field.
func (u *CreditReservationUpsertBulk) AddCeilingCredits(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddCeilingCredits(v)
	})
}

// UpdateCeilingCredits sets the "ceiling_credits" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateCeilingCredits() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateCeilingCredits()
	})
}

// SetPrepaidHold sets the "prepaid_hold" field.
func (u *CreditReservationUpsertBulk) SetPrepaidHold(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetPrepaidHold(v)
	})
}

// AddPrepaidHold adds v to the "prepaid_hold" field.
func (u *CreditReservationUpsertBulk) AddPrepaidHold(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddPrepaidHold(v)
	})
}

// UpdatePrepaidHold sets the "prepaid_hold" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdatePrepaidHold() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdatePrepaidHold()
	})
}

// SetEnterpriseHold sets the "enterprise_hold" field.
func (u *CreditReservationUpsertBulk) SetEnterpriseHold(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetEnterpriseHold(v)
	})
}

// AddEnterpriseHold adds v to the "enterprise_hold" field.
func (u *CreditReservationUpsertBulk) AddEnterpriseHold(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddEnterpriseHold(v)
	})
}

// UpdateEnterpriseHold sets the "enterprise_hold" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateEnterpriseHold() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateEnterpriseHold()
	})
}

// SetSettledCredits sets the "settled_credits" field.
func (u *CreditReservationUpsertBulk) SetSettledCredits(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettledCredits(v)
	})
}

// AddSettledCredits adds v to the "settled_credits" field.
func (u *CreditReservationUpsertBulk) AddSettledCredits(v int64) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.AddSettledCredits(v)
	})
}

// UpdateSettledCredits sets the "settled_credits" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateSettledCredits() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettledCredits()
	})
}

// SetSettlementIdempotencyKey sets the "settlement_idempotency_key" field.
func (u *CreditReservationUpsertBulk) SetSettlementIdempotencyKey(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettlementIdempotencyKey(v)
	})
}

// UpdateSettlementIdempotencyKey sets the "settlement_idempotency_key" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateSettlementIdempotencyKey() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettlementIdempotencyKey()
	})
}

// SetSettlementPayloadHash sets the "settlement_payload_hash" field.
func (u *CreditReservationUpsertBulk) SetSettlementPayloadHash(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettlementPayloadHash(v)
	})
}

// UpdateSettlementPayloadHash sets the "settlement_payload_hash" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateSettlementPayloadHash() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettlementPayloadHash()
	})
}

// SetRateVersion sets the "rate_version" field.
func (u *CreditReservationUpsertBulk) SetRateVersion(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetRateVersion(v)
	})
}

// UpdateRateVersion sets the "rate_version" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateRateVersion() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateRateVersion()
	})
}

// SetState sets the "state" field.
func (u *CreditReservationUpsertBulk) SetState(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateState() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateState()
	})
}

// SetProvider sets the "provider" field.
func (u *CreditReservationUpsertBulk) SetProvider(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateProvider() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *CreditReservationUpsertBulk) SetModel(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateModel() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateModel()
	})
}

// SetRequestID sets the "request_id" field.
func (u *CreditReservationUpsertBulk) SetRequestID(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateRequestID() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateRequestID()
	})
}

// SetAuthorizationExpiresAt sets the "authorization_expires_at" field.
func (u *CreditReservationUpsertBulk) SetAuthorizationExpiresAt(v time.Time) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetAuthorizationExpiresAt(v)
	})
}

// UpdateAuthorizationExpiresAt sets the "authorization_expires_at" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateAuthorizationExpiresAt() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateAuthorizationExpiresAt()
	})
}

// ClearAuthorizationExpiresAt clears the value of the "authorization_expires_at" field.
func (u *CreditReservationUpsertBulk) ClearAuthorizationExpiresAt() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearAuthorizationExpiresAt()
	})
}

// SetExecutionDeadline sets the "execution_deadline" field.
func (u *CreditReservationUpsertBulk) SetExecutionDeadline(v time.Time) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetExecutionDeadline(v)
	})
}

// UpdateExecutionDeadline sets the "execution_deadline" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateExecutionDeadline() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateExecutionDeadline()
	})
}

// ClearExecutionDeadline clears the value of the "execution_deadline" field.
func (u *CreditReservationUpsertBulk) ClearExecutionDeadline() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.ClearExecutionDeadline()
	})
}

// SetHoldLedgerGroupID sets the "hold_ledger_group_id" field.
func (u *CreditReservationUpsertBulk) SetHoldLedgerGroupID(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetHoldLedgerGroupID(v)
	})
}

// UpdateHoldLedgerGroupID sets the "hold_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateHoldLedgerGroupID() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateHoldLedgerGroupID()
	})
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (u *CreditReservationUpsertBulk) SetSettlementLedgerGroupID(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetSettlementLedgerGroupID(v)
	})
}

// UpdateSettlementLedgerGroupID sets the "settlement_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateSettlementLedgerGroupID() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateSettlementLedgerGroupID()
	})
}

// SetReleaseLedgerGroupID sets the "release_ledger_group_id" field.
func (u *CreditReservationUpsertBulk) SetReleaseLedgerGroupID(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetReleaseLedgerGroupID(v)
	})
}

// UpdateReleaseLedgerGroupID sets the "release_ledger_group_id" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateReleaseLedgerGroupID() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateReleaseLedgerGroupID()
	})
}

// SetUsageEventID sets the "usage_event_id" field.
func (u *CreditReservationUpsertBulk) SetUsageEventID(v string) *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.SetUsageEventID(v)
	})
}

// UpdateUsageEventID sets the "usage_event_id" field to the value that was provided on create.
func (u *CreditReservationUpsertBulk) UpdateUsageEventID() *CreditReservationUpsertBulk {
	return u.Update(func(s *CreditReservationUpsert) {
		s.UpdateUsageEventID()
	})
}

// Exec executes the query.
func (u *CreditReservationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the CreditReservationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for CreditReservationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditReservationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
