// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/currencies"
	"github.com/openmeterio/openmeter/openmeter/ent/db/creditcharge"
)

// CreditChargeCreate is the builder for creating a CreditCharge entity.
type CreditChargeCreate struct {
	config
	mutation *CreditChargeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNamespace sets the "namespace" field.
func (_c *CreditChargeCreate) SetNamespace(v string) *CreditChargeCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreditChargeCreate) SetCreatedAt(v time.Time) *CreditChargeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableCreatedAt(v *time.Time) *CreditChargeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CreditChargeCreate) SetUpdatedAt(v time.Time) *CreditChargeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableUpdatedAt(v *time.Time) *CreditChargeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CreditChargeCreate) SetDeletedAt(v time.Time) *CreditChargeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableDeletedAt(v *time.Time) *CreditChargeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetReservationID sets the "reservation_id" field.
func (_c *CreditChargeCreate) SetReservationID(v string) *CreditChargeCreate {
	_c.mutation.SetReservationID(v)
	return _c
}

// SetNillableReservationID sets the "reservation_id" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableReservationID(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetReservationID(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *CreditChargeCreate) SetCustomerID(v string) *CreditChargeCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *CreditChargeCreate) SetSubjectID(v string) *CreditChargeCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *CreditChargeCreate) SetOperation(v string) *CreditChargeCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *CreditChargeCreate) SetIdempotencyKey(v string) *CreditChargeCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetPayloadHash sets the "payload_hash" field.
func (_c *CreditChargeCreate) SetPayloadHash(v string) *CreditChargeCreate {
	_c.mutation.SetPayloadHash(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CreditChargeCreate) SetCurrency(v currencies.CurrencyReference) *CreditChargeCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetCustomCurrencyID sets the "custom_currency_id" field.
func (_c *CreditChargeCreate) SetCustomCurrencyID(v string) *CreditChargeCreate {
	_c.mutation.SetCustomCurrencyID(v)
	return _c
}

// SetNillableCustomCurrencyID sets the "custom_currency_id" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableCustomCurrencyID(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetCustomCurrencyID(*v)
	}
	return _c
}

// SetRatedLines sets the "rated_lines" field.
func (_c *CreditChargeCreate) SetRatedLines(v []json.RawMessage) *CreditChargeCreate {
	_c.mutation.SetRatedLines(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CreditChargeCreate) SetAmount(v int64) *CreditChargeCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetRateVersion sets the "rate_version" field.
func (_c *CreditChargeCreate) SetRateVersion(v string) *CreditChargeCreate {
	_c.mutation.SetRateVersion(v)
	return _c
}

// SetNillableRateVersion sets the "rate_version" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableRateVersion(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetRateVersion(*v)
	}
	return _c
}

// SetSettlementAllocations sets the "settlement_allocations" field.
func (_c *CreditChargeCreate) SetSettlementAllocations(v []json.RawMessage) *CreditChargeCreate {
	_c.mutation.SetSettlementAllocations(v)
	return _c
}

// SetState sets the "state" field.
func (_c *CreditChargeCreate) SetState(v creditcharge.State) *CreditChargeCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (_c *CreditChargeCreate) SetSettlementLedgerGroupID(v string) *CreditChargeCreate {
	_c.mutation.SetSettlementLedgerGroupID(v)
	return _c
}

// SetNillableSettlementLedgerGroupID sets the "settlement_ledger_group_id" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableSettlementLedgerGroupID(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetSettlementLedgerGroupID(*v)
	}
	return _c
}

// SetReversalLedgerGroupID sets the "reversal_ledger_group_id" field.
func (_c *CreditChargeCreate) SetReversalLedgerGroupID(v string) *CreditChargeCreate {
	_c.mutation.SetReversalLedgerGroupID(v)
	return _c
}

// SetNillableReversalLedgerGroupID sets the "reversal_ledger_group_id" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableReversalLedgerGroupID(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetReversalLedgerGroupID(*v)
	}
	return _c
}

// SetReversalIdempotencyKey sets the "reversal_idempotency_key" field.
func (_c *CreditChargeCreate) SetReversalIdempotencyKey(v string) *CreditChargeCreate {
	_c.mutation.SetReversalIdempotencyKey(v)
	return _c
}

// SetNillableReversalIdempotencyKey sets the "reversal_idempotency_key" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableReversalIdempotencyKey(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetReversalIdempotencyKey(*v)
	}
	return _c
}

// SetReversalPayloadHash sets the "reversal_payload_hash" field.
func (_c *CreditChargeCreate) SetReversalPayloadHash(v string) *CreditChargeCreate {
	_c.mutation.SetReversalPayloadHash(v)
	return _c
}

// SetNillableReversalPayloadHash sets the "reversal_payload_hash" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableReversalPayloadHash(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetReversalPayloadHash(*v)
	}
	return _c
}

// SetUsageEventID sets the "usage_event_id" field.
func (_c *CreditChargeCreate) SetUsageEventID(v string) *CreditChargeCreate {
	_c.mutation.SetUsageEventID(v)
	return _c
}

// SetNillableUsageEventID sets the "usage_event_id" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableUsageEventID(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetUsageEventID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CreditChargeCreate) SetID(v string) *CreditChargeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CreditChargeCreate) SetNillableID(v *string) *CreditChargeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CreditChargeMutation object of the builder.
func (_c *CreditChargeCreate) Mutation() *CreditChargeMutation {
	return _c.mutation
}

// Save creates the CreditCharge in the database.
func (_c *CreditChargeCreate) Save(ctx context.Context) (*CreditCharge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreditChargeCreate) SaveX(ctx context.Context) *CreditCharge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditChargeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditChargeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreditChargeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creditcharge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := creditcharge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RateVersion(); !ok {
		v := creditcharge.DefaultRateVersion
		_c.mutation.SetRateVersion(v)
	}
	if _, ok := _c.mutation.SettlementLedgerGroupID(); !ok {
		v := creditcharge.DefaultSettlementLedgerGroupID
		_c.mutation.SetSettlementLedgerGroupID(v)
	}
	if _, ok := _c.mutation.ReversalLedgerGroupID(); !ok {
		v := creditcharge.DefaultReversalLedgerGroupID
		_c.mutation.SetReversalLedgerGroupID(v)
	}
	if _, ok := _c.mutation.ReversalIdempotencyKey(); !ok {
		v := creditcharge.DefaultReversalIdempotencyKey
		_c.mutation.SetReversalIdempotencyKey(v)
	}
	if _, ok := _c.mutation.ReversalPayloadHash(); !ok {
		v := creditcharge.DefaultReversalPayloadHash
		_c.mutation.SetReversalPayloadHash(v)
	}
	if _, ok := _c.mutation.UsageEventID(); !ok {
		v := creditcharge.DefaultUsageEventID
		_c.mutation.SetUsageEventID(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := creditcharge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreditChargeCreate) check() error {
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`db: missing required field "CreditCharge.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := creditcharge.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`db: validator failed for field "CreditCharge.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "CreditCharge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "CreditCharge.updated_at"`)}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`db: missing required field "CreditCharge.customer_id"`)}
	}
	if v, ok := _c.mutation.CustomerID(); ok {
		if err := creditcharge.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`db: validator failed for field "CreditCharge.customer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`db: missing required field "CreditCharge.subject_id"`)}
	}
	if v, ok := _c.mutation.SubjectID(); ok {
		if err := creditcharge.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`db: validator failed for field "CreditCharge.subject_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`db: missing required field "CreditCharge.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := creditcharge.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`db: validator failed for field "CreditCharge.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`db: missing required field "CreditCharge.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := creditcharge.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`db: validator failed for field "CreditCharge.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayloadHash(); !ok {
		return &ValidationError{Name: "payload_hash", err: errors.New(`db: missing required field "CreditCharge.payload_hash"`)}
	}
	if v, ok := _c.mutation.PayloadHash(); ok {
		if err := creditcharge.PayloadHashValidator(v); err != nil {
			return &ValidationError{Name: "payload_hash", err: fmt.Errorf(`db: validator failed for field "CreditCharge.payload_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`db: missing required field "CreditCharge.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`db: validator failed for field "CreditCharge.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RatedLines(); !ok {
		return &ValidationError{Name: "rated_lines", err: errors.New(`db: missing required field "CreditCharge.rated_lines"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`db: missing required field "CreditCharge.amount"`)}
	}
	if _, ok := _c.mutation.RateVersion(); !ok {
		return &ValidationError{Name: "rate_version", err: errors.New(`db: missing required field "CreditCharge.rate_version"`)}
	}
	if _, ok := _c.mutation.SettlementAllocations(); !ok {
		return &ValidationError{Name: "settlement_allocations", err: errors.New(`db: missing required field "CreditCharge.settlement_allocations"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`db: missing required field "CreditCharge.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := creditcharge.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`db: validator failed for field "CreditCharge.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettlementLedgerGroupID(); !ok {
		return &ValidationError{Name: "settlement_ledger_group_id", err: errors.New(`db: missing required field "CreditCharge.settlement_ledger_group_id"`)}
	}
	if _, ok := _c.mutation.ReversalLedgerGroupID(); !ok {
		return &ValidationError{Name: "reversal_ledger_group_id", err: errors.New(`db: missing required field "CreditCharge.reversal_ledger_group_id"`)}
	}
	if _, ok := _c.mutation.ReversalIdempotencyKey(); !ok {
		return &ValidationError{Name: "reversal_idempotency_key", err: errors.New(`db: missing required field "CreditCharge.reversal_idempotency_key"`)}
	}
	if _, ok := _c.mutation.ReversalPayloadHash(); !ok {
		return &ValidationError{Name: "reversal_payload_hash", err: errors.New(`db: missing required field "CreditCharge.reversal_payload_hash"`)}
	}
	if _, ok := _c.mutation.UsageEventID(); !ok {
		return &ValidationError{Name: "usage_event_id", err: errors.New(`db: missing required field "CreditCharge.usage_event_id"`)}
	}
	return nil
}

func (_c *CreditChargeCreate) sqlSave(ctx context.Context) (*CreditCharge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CreditCharge.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreditChargeCreate) createSpec() (*CreditCharge, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditCharge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creditcharge.Table, sqlgraph.NewFieldSpec(creditcharge.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(creditcharge.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creditcharge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(creditcharge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(creditcharge.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ReservationID(); ok {
		_spec.SetField(creditcharge.FieldReservationID, field.TypeString, value)
		_node.ReservationID = &value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(creditcharge.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(creditcharge.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(creditcharge.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(creditcharge.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.PayloadHash(); ok {
		_spec.SetField(creditcharge.FieldPayloadHash, field.TypeString, value)
		_node.PayloadHash = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(creditcharge.FieldCurrency, field.TypeJSON, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.CustomCurrencyID(); ok {
		_spec.SetField(creditcharge.FieldCustomCurrencyID, field.TypeString, value)
		_node.CustomCurrencyID = &value
	}
	if value, ok := _c.mutation.RatedLines(); ok {
		_spec.SetField(creditcharge.FieldRatedLines, field.TypeJSON, value)
		_node.RatedLines = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(creditcharge.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.RateVersion(); ok {
		_spec.SetField(creditcharge.FieldRateVersion, field.TypeString, value)
		_node.RateVersion = value
	}
	if value, ok := _c.mutation.SettlementAllocations(); ok {
		_spec.SetField(creditcharge.FieldSettlementAllocations, field.TypeJSON, value)
		_node.SettlementAllocations = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(creditcharge.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.SettlementLedgerGroupID(); ok {
		_spec.SetField(creditcharge.FieldSettlementLedgerGroupID, field.TypeString, value)
		_node.SettlementLedgerGroupID = value
	}
	if value, ok := _c.mutation.ReversalLedgerGroupID(); ok {
		_spec.SetField(creditcharge.FieldReversalLedgerGroupID, field.TypeString, value)
		_node.ReversalLedgerGroupID = value
	}
	if value, ok := _c.mutation.ReversalIdempotencyKey(); ok {
		_spec.SetField(creditcharge.FieldReversalIdempotencyKey, field.TypeString, value)
		_node.ReversalIdempotencyKey = value
	}
	if value, ok := _c.mutation.ReversalPayloadHash(); ok {
		_spec.SetField(creditcharge.FieldReversalPayloadHash, field.TypeString, value)
		_node.ReversalPayloadHash = value
	}
	if value, ok := _c.mutation.UsageEventID(); ok {
		_spec.SetField(creditcharge.FieldUsageEventID, field.TypeString, value)
		_node.UsageEventID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditCharge.Create().
//		SetNamespace(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditChargeUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditChargeCreate) OnConflict(opts ...sql.ConflictOption) *CreditChargeUpsertOne {
	_c.conflict = opts
	return &CreditChargeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditCharge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditChargeCreate) OnConflictColumns(columns ...string) *CreditChargeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditChargeUpsertOne{
		create: _c,
	}
}

type (
	// CreditChargeUpsertOne is the builder for "upsert"-ing
	//  one CreditCharge node.
	CreditChargeUpsertOne struct {
		create *CreditChargeCreate
	}

	// CreditChargeUpsert is the "OnConflict" setter.
	CreditChargeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CreditChargeUpsert) SetUpdatedAt(v time.Time) *CreditChargeUpsert {
	u.Set(creditcharge.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateUpdatedAt() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CreditChargeUpsert) SetDeletedAt(v time.Time) *CreditChargeUpsert {
	u.Set(creditcharge.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateDeletedAt() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CreditChargeUpsert) ClearDeletedAt() *CreditChargeUpsert {
	u.SetNull(creditcharge.FieldDeletedAt)
	return u
}

// SetRatedLines sets the "rated_lines" field.
func (u *CreditChargeUpsert) SetRatedLines(v []json.RawMessage) *CreditChargeUpsert {
	u.Set(creditcharge.FieldRatedLines, v)
	return u
}

// UpdateRatedLines sets the "rated_lines" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateRatedLines() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldRatedLines)
	return u
}

// SetAmount sets the "amount" field.
func (u *CreditChargeUpsert) SetAmount(v int64) *CreditChargeUpsert {
	u.Set(creditcharge.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateAmount() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CreditChargeUpsert) AddAmount(v int64) *CreditChargeUpsert {
	u.Add(creditcharge.FieldAmount, v)
	return u
}

// SetRateVersion sets the "rate_version" field.
func (u *CreditChargeUpsert) SetRateVersion(v string) *CreditChargeUpsert {
	u.Set(creditcharge.FieldRateVersion, v)
	return u
}

// UpdateRateVersion sets the "rate_version" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateRateVersion() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldRateVersion)
	return u
}

// SetSettlementAllocations sets the "settlement_allocations" field.
func (u *CreditChargeUpsert) SetSettlementAllocations(v []json.RawMessage) *CreditChargeUpsert {
	u.Set(creditcharge.FieldSettlementAllocations, v)
	return u
}

// UpdateSettlementAllocations sets the "settlement_allocations" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateSettlementAllocations() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldSettlementAllocations)
	return u
}

// SetState sets the "state" field.
func (u *CreditChargeUpsert) SetState(v creditcharge.State) *CreditChargeUpsert {
	u.Set(creditcharge.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateState() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldState)
	return u
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (u *CreditChargeUpsert) SetSettlementLedgerGroupID(v string) *CreditChargeUpsert {
	u.Set(creditcharge.FieldSettlementLedgerGroupID, v)
	return u
}

// UpdateSettlementLedgerGroupID sets the "settlement_ledger_group_id" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateSettlementLedgerGroupID() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldSettlementLedgerGroupID)
	return u
}

// SetReversalLedgerGroupID sets the "reversal_ledger_group_id" field.
func (u *CreditChargeUpsert) SetReversalLedgerGroupID(v string) *CreditChargeUpsert {
	u.Set(creditcharge.FieldReversalLedgerGroupID, v)
	return u
}

// UpdateReversalLedgerGroupID sets the "reversal_ledger_group_id" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateReversalLedgerGroupID() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldReversalLedgerGroupID)
	return u
}

// SetReversalIdempotencyKey sets the "reversal_idempotency_key" field.
func (u *CreditChargeUpsert) SetReversalIdempotencyKey(v string) *CreditChargeUpsert {
	u.Set(creditcharge.FieldReversalIdempotencyKey, v)
	return u
}

// UpdateReversalIdempotencyKey sets the "reversal_idempotency_key" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateReversalIdempotencyKey() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldReversalIdempotencyKey)
	return u
}

// SetReversalPayloadHash sets the "reversal_payload_hash" field.
func (u *CreditChargeUpsert) SetReversalPayloadHash(v string) *CreditChargeUpsert {
	u.Set(creditcharge.FieldReversalPayloadHash, v)
	return u
}

// UpdateReversalPayloadHash sets the "reversal_payload_hash" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateReversalPayloadHash() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldReversalPayloadHash)
	return u
}

// SetUsageEventID sets the "usage_event_id" field.
func (u *CreditChargeUpsert) SetUsageEventID(v string) *CreditChargeUpsert {
	u.Set(creditcharge.FieldUsageEventID, v)
	return u
}

// UpdateUsageEventID sets the "usage_event_id" field to the value that was provided on create.
func (u *CreditChargeUpsert) UpdateUsageEventID() *CreditChargeUpsert {
	u.SetExcluded(creditcharge.FieldUsageEventID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CreditCharge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(creditcharge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreditChargeUpsertOne) UpdateNewValues() *CreditChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(creditcharge.FieldID)
		}
		if _, exists := u.create.mutation.Namespace(); exists {
			s.SetIgnore(creditcharge.FieldNamespace)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creditcharge.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ReservationID(); exists {
			s.SetIgnore(creditcharge.FieldReservationID)
		}
		if _, exists := u.create.mutation.CustomerID(); exists {
			s.SetIgnore(creditcharge.FieldCustomerID)
		}
		if _, exists := u.create.mutation.SubjectID(); exists {
			s.SetIgnore(creditcharge.FieldSubjectID)
		}
		if _, exists := u.create.mutation.Operation(); exists {
			s.SetIgnore(creditcharge.FieldOperation)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(creditcharge.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.PayloadHash(); exists {
			s.SetIgnore(creditcharge.FieldPayloadHash)
		}
		if _, exists := u.create.mutation.Currency(); exists {
			s.SetIgnore(creditcharge.FieldCurrency)
		}
		if _, exists := u.create.mutation.CustomCurrencyID(); exists {
			s.SetIgnore(creditcharge.FieldCustomCurrencyID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditCharge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreditChargeUpsertOne) Ignore() *CreditChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditChargeUpsertOne) DoNothing() *CreditChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditChargeCreate.OnConflict
// documentation for more info.
func (u *CreditChargeUpsertOne) Update(set func(*CreditChargeUpsert)) *CreditChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditChargeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreditChargeUpsertOne) SetUpdatedAt(v time.Time) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateUpdatedAt() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CreditChargeUpsertOne) SetDeletedAt(v time.Time) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateDeletedAt() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CreditChargeUpsertOne) ClearDeletedAt() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRatedLines sets the "rated_lines" field.
func (u *CreditChargeUpsertOne) SetRatedLines(v []json.RawMessage) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetRatedLines(v)
	})
}

// UpdateRatedLines sets the "rated_lines" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateRatedLines() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateRatedLines()
	})
}

// SetAmount sets the "amount" field.
func (u *CreditChargeUpsertOne) SetAmount(v int64) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CreditChargeUpsertOne) AddAmount(v int64) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateAmount() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateAmount()
	})
}

// SetRateVersion sets the "rate_version" field.
func (u *CreditChargeUpsertOne) SetRateVersion(v string) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetRateVersion(v)
	})
}

// UpdateRateVersion sets the "rate_version" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateRateVersion() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateRateVersion()
	})
}

// SetSettlementAllocations sets the "settlement_allocations" field.
func (u *CreditChargeUpsertOne) SetSettlementAllocations(v []json.RawMessage) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetSettlementAllocations(v)
	})
}

// UpdateSettlementAllocations sets the "settlement_allocations" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateSettlementAllocations() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateSettlementAllocations()
	})
}

// SetState sets the "state" field.
func (u *CreditChargeUpsertOne) SetState(v creditcharge.State) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateState() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateState()
	})
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (u *CreditChargeUpsertOne) SetSettlementLedgerGroupID(v string) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetSettlementLedgerGroupID(v)
	})
}

// UpdateSettlementLedgerGroupID sets the "settlement_ledger_group_id" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateSettlementLedgerGroupID() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateSettlementLedgerGroupID()
	})
}

// SetReversalLedgerGroupID sets the "reversal_ledger_group_id" field.
func (u *CreditChargeUpsertOne) SetReversalLedgerGroupID(v string) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetReversalLedgerGroupID(v)
	})
}

// UpdateReversalLedgerGroupID sets the "reversal_ledger_group_id" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateReversalLedgerGroupID() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateReversalLedgerGroupID()
	})
}

// SetReversalIdempotencyKey sets the "reversal_idempotency_key" field.
func (u *CreditChargeUpsertOne) SetReversalIdempotencyKey(v string) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetReversalIdempotencyKey(v)
	})
}

// UpdateReversalIdempotencyKey sets the "reversal_idempotency_key" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateReversalIdempotencyKey() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateReversalIdempotencyKey()
	})
}

// SetReversalPayloadHash sets the "reversal_payload_hash" field.
func (u *CreditChargeUpsertOne) SetReversalPayloadHash(v string) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetReversalPayloadHash(v)
	})
}

// UpdateReversalPayloadHash sets the "reversal_payload_hash" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateReversalPayloadHash() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateReversalPayloadHash()
	})
}

// SetUsageEventID sets the "usage_event_id" field.
func (u *CreditChargeUpsertOne) SetUsageEventID(v string) *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetUsageEventID(v)
	})
}

// UpdateUsageEventID sets the "usage_event_id" field to the value that was provided on create.
func (u *CreditChargeUpsertOne) UpdateUsageEventID() *CreditChargeUpsertOne {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateUsageEventID()
	})
}

// Exec executes the query.
func (u *CreditChargeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for CreditChargeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditChargeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreditChargeUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: CreditChargeUpsertOne.ID is not supported by MySQL driver. Use CreditChargeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreditChargeUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreditChargeCreateBulk is the builder for creating many CreditCharge entities in bulk.
type CreditChargeCreateBulk struct {
	config
	err      error
	builders []*CreditChargeCreate
	conflict []sql.ConflictOption
}

// Save creates the CreditCharge entities in the database.
func (_c *CreditChargeCreateBulk) Save(ctx context.Context) ([]*CreditCharge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreditCharge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditChargeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreditChargeCreateBulk) SaveX(ctx context.Context) []*CreditCharge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditChargeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditChargeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditCharge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditChargeUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditChargeCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreditChargeUpsertBulk {
	_c.conflict = opts
	return &CreditChargeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditCharge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditChargeCreateBulk) OnConflictColumns(columns ...string) *CreditChargeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditChargeUpsertBulk{
		create: _c,
	}
}

// CreditChargeUpsertBulk is the builder for "upsert"-ing
// a bulk of CreditCharge nodes.
type CreditChargeUpsertBulk struct {
	create *CreditChargeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreditCharge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(creditcharge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreditChargeUpsertBulk) UpdateNewValues() *CreditChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(creditcharge.FieldID)
			}
			if _, exists := b.mutation.Namespace(); exists {
				s.SetIgnore(creditcharge.FieldNamespace)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creditcharge.FieldCreatedAt)
			}
			if _, exists := b.mutation.ReservationID(); exists {
				s.SetIgnore(creditcharge.FieldReservationID)
			}
			if _, exists := b.mutation.CustomerID(); exists {
				s.SetIgnore(creditcharge.FieldCustomerID)
			}
			if _, exists := b.mutation.SubjectID(); exists {
				s.SetIgnore(creditcharge.FieldSubjectID)
			}
			if _, exists := b.mutation.Operation(); exists {
				s.SetIgnore(creditcharge.FieldOperation)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(creditcharge.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.PayloadHash(); exists {
				s.SetIgnore(creditcharge.FieldPayloadHash)
			}
			if _, exists := b.mutation.Currency(); exists {
				s.SetIgnore(creditcharge.FieldCurrency)
			}
			if _, exists := b.mutation.CustomCurrencyID(); exists {
				s.SetIgnore(creditcharge.FieldCustomCurrencyID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditCharge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreditChargeUpsertBulk) Ignore() *CreditChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditChargeUpsertBulk) DoNothing() *CreditChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditChargeCreateBulk.OnConflict
// documentation for more info.
func (u *CreditChargeUpsertBulk) Update(set func(*CreditChargeUpsert)) *CreditChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditChargeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreditChargeUpsertBulk) SetUpdatedAt(v time.Time) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateUpdatedAt() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CreditChargeUpsertBulk) SetDeletedAt(v time.Time) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateDeletedAt() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CreditChargeUpsertBulk) ClearDeletedAt() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRatedLines sets the "rated_lines" field.
func (u *CreditChargeUpsertBulk) SetRatedLines(v []json.RawMessage) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetRatedLines(v)
	})
}

// UpdateRatedLines sets the "rated_lines" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateRatedLines() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateRatedLines()
	})
}

// SetAmount sets the "amount" field.
func (u *CreditChargeUpsertBulk) SetAmount(v int64) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CreditChargeUpsertBulk) AddAmount(v int64) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateAmount() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateAmount()
	})
}

// SetRateVersion sets the "rate_version" field.
func (u *CreditChargeUpsertBulk) SetRateVersion(v string) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetRateVersion(v)
	})
}

// UpdateRateVersion sets the "rate_version" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateRateVersion() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateRateVersion()
	})
}

// SetSettlementAllocations sets the "settlement_allocations" field.
func (u *CreditChargeUpsertBulk) SetSettlementAllocations(v []json.RawMessage) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetSettlementAllocations(v)
	})
}

// UpdateSettlementAllocations sets the "settlement_allocations" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateSettlementAllocations() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateSettlementAllocations()
	})
}

// SetState sets the "state" field.
func (u *CreditChargeUpsertBulk) SetState(v creditcharge.State) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateState() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateState()
	})
}

// SetSettlementLedgerGroupID sets the "settlement_ledger_group_id" field.
func (u *CreditChargeUpsertBulk) SetSettlementLedgerGroupID(v string) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetSettlementLedgerGroupID(v)
	})
}

// UpdateSettlementLedgerGroupID sets the "settlement_ledger_group_id" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateSettlementLedgerGroupID() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateSettlementLedgerGroupID()
	})
}

// SetReversalLedgerGroupID sets the "reversal_ledger_group_id" field.
func (u *CreditChargeUpsertBulk) SetReversalLedgerGroupID(v string) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetReversalLedgerGroupID(v)
	})
}

// UpdateReversalLedgerGroupID sets the "reversal_ledger_group_id" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateReversalLedgerGroupID() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateReversalLedgerGroupID()
	})
}

// SetReversalIdempotencyKey sets the "reversal_idempotency_key" field.
func (u *CreditChargeUpsertBulk) SetReversalIdempotencyKey(v string) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetReversalIdempotencyKey(v)
	})
}

// UpdateReversalIdempotencyKey sets the "reversal_idempotency_key" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateReversalIdempotencyKey() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateReversalIdempotencyKey()
	})
}

// SetReversalPayloadHash sets the "reversal_payload_hash" field.
func (u *CreditChargeUpsertBulk) SetReversalPayloadHash(v string) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetReversalPayloadHash(v)
	})
}

// UpdateReversalPayloadHash sets the "reversal_payload_hash" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateReversalPayloadHash() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateReversalPayloadHash()
	})
}

// SetUsageEventID sets the "usage_event_id" field.
func (u *CreditChargeUpsertBulk) SetUsageEventID(v string) *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.SetUsageEventID(v)
	})
}

// UpdateUsageEventID sets the "usage_event_id" field to the value that was provided on create.
func (u *CreditChargeUpsertBulk) UpdateUsageEventID() *CreditChargeUpsertBulk {
	return u.Update(func(s *CreditChargeUpsert) {
		s.UpdateUsageEventID()
	})
}

// Exec executes the query.
func (u *CreditChargeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the CreditChargeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for CreditChargeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditChargeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
