// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/alpacahq/alpacadecimal"
	"github.com/openmeterio/openmeter/openmeter/ent/db/manualresourcecost"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
	"github.com/openmeterio/openmeter/pkg/models"
)

// ManualResourceCostUpdate is the builder for updating ManualResourceCost entities.
type ManualResourceCostUpdate struct {
	config
	hooks    []Hook
	mutation *ManualResourceCostMutation
}

// Where appends a list predicates to the ManualResourceCostUpdate builder.
func (_u *ManualResourceCostUpdate) Where(ps ...predicate.ManualResourceCost) *ManualResourceCostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnotations sets the "annotations" field.
func (_u *ManualResourceCostUpdate) SetAnnotations(v models.Annotations) *ManualResourceCostUpdate {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *ManualResourceCostUpdate) ClearAnnotations() *ManualResourceCostUpdate {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManualResourceCostUpdate) SetUpdatedAt(v time.Time) *ManualResourceCostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ManualResourceCostUpdate) SetDeletedAt(v time.Time) *ManualResourceCostUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableDeletedAt(v *time.Time) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ManualResourceCostUpdate) ClearDeletedAt() *ManualResourceCostUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetResourceCode sets the "resource_code" field.
func (_u *ManualResourceCostUpdate) SetResourceCode(v string) *ManualResourceCostUpdate {
	_u.mutation.SetResourceCode(v)
	return _u
}

// SetNillableResourceCode sets the "resource_code" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableResourceCode(v *string) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetResourceCode(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ManualResourceCostUpdate) SetProvider(v string) *ManualResourceCostUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableProvider(v *string) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *ManualResourceCostUpdate) ClearProvider() *ManualResourceCostUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetModel sets the "model" field.
func (_u *ManualResourceCostUpdate) SetModel(v string) *ManualResourceCostUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableModel(v *string) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *ManualResourceCostUpdate) ClearModel() *ManualResourceCostUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetCostCurrency sets the "cost_currency" field.
func (_u *ManualResourceCostUpdate) SetCostCurrency(v string) *ManualResourceCostUpdate {
	_u.mutation.SetCostCurrency(v)
	return _u
}

// SetNillableCostCurrency sets the "cost_currency" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableCostCurrency(v *string) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetCostCurrency(*v)
	}
	return _u
}

// SetCostAmount sets the "cost_amount" field.
func (_u *ManualResourceCostUpdate) SetCostAmount(v alpacadecimal.Decimal) *ManualResourceCostUpdate {
	_u.mutation.SetCostAmount(v)
	return _u
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableCostAmount(v *alpacadecimal.Decimal) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetCostAmount(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ManualResourceCostUpdate) SetSource(v string) *ManualResourceCostUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableSource(v *string) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *ManualResourceCostUpdate) SetEffectiveFrom(v time.Time) *ManualResourceCostUpdate {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableEffectiveFrom(v *time.Time) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetEffectiveTo sets the "effective_to" field.
func (_u *ManualResourceCostUpdate) SetEffectiveTo(v time.Time) *ManualResourceCostUpdate {
	_u.mutation.SetEffectiveTo(v)
	return _u
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_u *ManualResourceCostUpdate) SetNillableEffectiveTo(v *time.Time) *ManualResourceCostUpdate {
	if v != nil {
		_u.SetEffectiveTo(*v)
	}
	return _u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (_u *ManualResourceCostUpdate) ClearEffectiveTo() *ManualResourceCostUpdate {
	_u.mutation.ClearEffectiveTo()
	return _u
}

// Mutation returns the ManualResourceCostMutation object of the builder.
func (_u *ManualResourceCostUpdate) Mutation() *ManualResourceCostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManualResourceCostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManualResourceCostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManualResourceCostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManualResourceCostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManualResourceCostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := manualresourcecost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManualResourceCostUpdate) check() error {
	if v, ok := _u.mutation.ResourceCode(); ok {
		if err := manualresourcecost.ResourceCodeValidator(v); err != nil {
			return &ValidationError{Name: "resource_code", err: fmt.Errorf(`db: validator failed for field "ManualResourceCost.resource_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ManualResourceCostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(manualresourcecost.Table, manualresourcecost.Columns, sqlgraph.NewFieldSpec(manualresourcecost.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(manualresourcecost.FieldAnnotations, field.TypeJSON, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(manualresourcecost.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(manualresourcecost.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(manualresourcecost.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(manualresourcecost.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResourceCode(); ok {
		_spec.SetField(manualresourcecost.FieldResourceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(manualresourcecost.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(manualresourcecost.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(manualresourcecost.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(manualresourcecost.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.CostCurrency(); ok {
		_spec.SetField(manualresourcecost.FieldCostCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostAmount(); ok {
		_spec.SetField(manualresourcecost.FieldCostAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(manualresourcecost.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(manualresourcecost.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EffectiveTo(); ok {
		_spec.SetField(manualresourcecost.FieldEffectiveTo, field.TypeTime, value)
	}
	if _u.mutation.EffectiveToCleared() {
		_spec.ClearField(manualresourcecost.FieldEffectiveTo, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{manualresourcecost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManualResourceCostUpdateOne is the builder for updating a single ManualResourceCost entity.
type ManualResourceCostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ManualResourceCostMutation
}

// SetAnnotations sets the "annotations" field.
func (_u *ManualResourceCostUpdateOne) SetAnnotations(v models.Annotations) *ManualResourceCostUpdateOne {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *ManualResourceCostUpdateOne) ClearAnnotations() *ManualResourceCostUpdateOne {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManualResourceCostUpdateOne) SetUpdatedAt(v time.Time) *ManualResourceCostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ManualResourceCostUpdateOne) SetDeletedAt(v time.Time) *ManualResourceCostUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableDeletedAt(v *time.Time) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ManualResourceCostUpdateOne) ClearDeletedAt() *ManualResourceCostUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetResourceCode sets the "resource_code" field.
func (_u *ManualResourceCostUpdateOne) SetResourceCode(v string) *ManualResourceCostUpdateOne {
	_u.mutation.SetResourceCode(v)
	return _u
}

// SetNillableResourceCode sets the "resource_code" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableResourceCode(v *string) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetResourceCode(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ManualResourceCostUpdateOne) SetProvider(v string) *ManualResourceCostUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableProvider(v *string) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *ManualResourceCostUpdateOne) ClearProvider() *ManualResourceCostUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetModel sets the "model" field.
func (_u *ManualResourceCostUpdateOne) SetModel(v string) *ManualResourceCostUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableModel(v *string) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *ManualResourceCostUpdateOne) ClearModel() *ManualResourceCostUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetCostCurrency sets the "cost_currency" field.
func (_u *ManualResourceCostUpdateOne) SetCostCurrency(v string) *ManualResourceCostUpdateOne {
	_u.mutation.SetCostCurrency(v)
	return _u
}

// SetNillableCostCurrency sets the "cost_currency" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableCostCurrency(v *string) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetCostCurrency(*v)
	}
	return _u
}

// SetCostAmount sets the "cost_amount" field.
func (_u *ManualResourceCostUpdateOne) SetCostAmount(v alpacadecimal.Decimal) *ManualResourceCostUpdateOne {
	_u.mutation.SetCostAmount(v)
	return _u
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableCostAmount(v *alpacadecimal.Decimal) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetCostAmount(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ManualResourceCostUpdateOne) SetSource(v string) *ManualResourceCostUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableSource(v *string) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *ManualResourceCostUpdateOne) SetEffectiveFrom(v time.Time) *ManualResourceCostUpdateOne {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableEffectiveFrom(v *time.Time) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetEffectiveTo sets the "effective_to" field.
func (_u *ManualResourceCostUpdateOne) SetEffectiveTo(v time.Time) *ManualResourceCostUpdateOne {
	_u.mutation.SetEffectiveTo(v)
	return _u
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_u *ManualResourceCostUpdateOne) SetNillableEffectiveTo(v *time.Time) *ManualResourceCostUpdateOne {
	if v != nil {
		_u.SetEffectiveTo(*v)
	}
	return _u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (_u *ManualResourceCostUpdateOne) ClearEffectiveTo() *ManualResourceCostUpdateOne {
	_u.mutation.ClearEffectiveTo()
	return _u
}

// Mutation returns the ManualResourceCostMutation object of the builder.
func (_u *ManualResourceCostUpdateOne) Mutation() *ManualResourceCostMutation {
	return _u.mutation
}

// Where appends a list predicates to the ManualResourceCostUpdate builder.
func (_u *ManualResourceCostUpdateOne) Where(ps ...predicate.ManualResourceCost) *ManualResourceCostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManualResourceCostUpdateOne) Select(field string, fields ...string) *ManualResourceCostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ManualResourceCost entity.
func (_u *ManualResourceCostUpdateOne) Save(ctx context.Context) (*ManualResourceCost, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManualResourceCostUpdateOne) SaveX(ctx context.Context) *ManualResourceCost {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManualResourceCostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManualResourceCostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManualResourceCostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := manualresourcecost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManualResourceCostUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceCode(); ok {
		if err := manualresourcecost.ResourceCodeValidator(v); err != nil {
			return &ValidationError{Name: "resource_code", err: fmt.Errorf(`db: validator failed for field "ManualResourceCost.resource_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ManualResourceCostUpdateOne) sqlSave(ctx context.Context) (_node *ManualResourceCost, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(manualresourcecost.Table, manualresourcecost.Columns, sqlgraph.NewFieldSpec(manualresourcecost.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "ManualResourceCost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, manualresourcecost.FieldID)
		for _, f := range fields {
			if !manualresourcecost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != manualresourcecost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(manualresourcecost.FieldAnnotations, field.TypeJSON, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(manualresourcecost.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(manualresourcecost.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(manualresourcecost.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(manualresourcecost.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResourceCode(); ok {
		_spec.SetField(manualresourcecost.FieldResourceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(manualresourcecost.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(manualresourcecost.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(manualresourcecost.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(manualresourcecost.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.CostCurrency(); ok {
		_spec.SetField(manualresourcecost.FieldCostCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostAmount(); ok {
		_spec.SetField(manualresourcecost.FieldCostAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(manualresourcecost.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(manualresourcecost.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EffectiveTo(); ok {
		_spec.SetField(manualresourcecost.FieldEffectiveTo, field.TypeTime, value)
	}
	if _u.mutation.EffectiveToCleared() {
		_spec.ClearField(manualresourcecost.FieldEffectiveTo, field.TypeTime)
	}
	_node = &ManualResourceCost{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{manualresourcecost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
