// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/commerceorder"
	"github.com/openmeterio/openmeter/openmeter/ent/db/paymentattempt"
)

// PaymentAttempt is the model entity for the PaymentAttempt schema.
type PaymentAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CommerceOrderID holds the value of the "commerce_order_id" field.
	CommerceOrderID string `json:"commerce_order_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider paymentattempt.Provider `json:"provider,omitempty"`
	// ProviderOrderID holds the value of the "provider_order_id" field.
	ProviderOrderID *string `json:"provider_order_id,omitempty"`
	// ProviderPaymentID holds the value of the "provider_payment_id" field.
	ProviderPaymentID *string `json:"provider_payment_id,omitempty"`
	// Status holds the value of the "status" field.
	Status paymentattempt.Status `json:"status,omitempty"`
	// ProviderSessionID holds the value of the "provider_session_id" field.
	ProviderSessionID *string `json:"provider_session_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents int64 `json:"amount_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentAttemptQuery when eager-loading is set.
	Edges        PaymentAttemptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentAttemptEdges holds the relations/edges for other nodes in the graph.
type PaymentAttemptEdges struct {
	// Order holds the value of the order edge.
	Order *CommerceOrder `json:"order,omitempty"`
	// Facts holds the value of the facts edge.
	Facts []*PaymentFact `json:"facts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentAttemptEdges) OrderOrErr() (*CommerceOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: commerceorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// FactsOrErr returns the Facts value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentAttemptEdges) FactsOrErr() ([]*PaymentFact, error) {
	if e.loadedTypes[1] {
		return e.Facts, nil
	}
	return nil, &NotLoadedError{edge: "facts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentattempt.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case paymentattempt.FieldID, paymentattempt.FieldNamespace, paymentattempt.FieldCommerceOrderID, paymentattempt.FieldCustomerID, paymentattempt.FieldProvider, paymentattempt.FieldProviderOrderID, paymentattempt.FieldProviderPaymentID, paymentattempt.FieldStatus, paymentattempt.FieldProviderSessionID, paymentattempt.FieldIdempotencyKey, paymentattempt.FieldCurrency:
			values[i] = new(sql.NullString)
		case paymentattempt.FieldCreatedAt, paymentattempt.FieldUpdatedAt, paymentattempt.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentAttempt fields.
func (_m *PaymentAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentattempt.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case paymentattempt.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case paymentattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentattempt.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paymentattempt.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case paymentattempt.FieldCommerceOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field commerce_order_id", values[i])
			} else if value.Valid {
				_m.CommerceOrderID = value.String
			}
		case paymentattempt.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = value.String
			}
		case paymentattempt.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = paymentattempt.Provider(value.String)
			}
		case paymentattempt.FieldProviderOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_order_id", values[i])
			} else if value.Valid {
				_m.ProviderOrderID = new(string)
				*_m.ProviderOrderID = value.String
			}
		case paymentattempt.FieldProviderPaymentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_payment_id", values[i])
			} else if value.Valid {
				_m.ProviderPaymentID = new(string)
				*_m.ProviderPaymentID = value.String
			}
		case paymentattempt.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = paymentattempt.Status(value.String)
			}
		case paymentattempt.FieldProviderSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_session_id", values[i])
			} else if value.Valid {
				_m.ProviderSessionID = new(string)
				*_m.ProviderSessionID = value.String
			}
		case paymentattempt.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case paymentattempt.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = value.Int64
			}
		case paymentattempt.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the PaymentAttempt entity.
func (_m *PaymentAttempt) QueryOrder() *CommerceOrderQuery {
	return NewPaymentAttemptClient(_m.config).QueryOrder(_m)
}

// QueryFacts queries the "facts" edge of the PaymentAttempt entity.
func (_m *PaymentAttempt) QueryFacts() *PaymentFactQuery {
	return NewPaymentAttemptClient(_m.config).QueryFacts(_m)
}

// Update returns a builder for updating this PaymentAttempt.
// Note that you need to call PaymentAttempt.Unwrap() before calling this method if this PaymentAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentAttempt) Update() *PaymentAttemptUpdateOne {
	return NewPaymentAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentAttempt) Unwrap() *PaymentAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: PaymentAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("commerce_order_id=")
	builder.WriteString(_m.CommerceOrderID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(_m.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	if v := _m.ProviderOrderID; v != nil {
		builder.WriteString("provider_order_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderPaymentID; v != nil {
		builder.WriteString("provider_payment_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ProviderSessionID; v != nil {
		builder.WriteString("provider_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteByte(')')
	return builder.String()
}

// PaymentAttempts is a parsable slice of PaymentAttempt.
type PaymentAttempts []*PaymentAttempt
