// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/paymentattempt"
	"github.com/openmeterio/openmeter/openmeter/ent/db/paymentfact"
)

// PaymentFact is the model entity for the PaymentFact schema.
type PaymentFact struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RawHash holds the value of the "raw_hash" field.
	RawHash string `json:"raw_hash,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider paymentfact.Provider `json:"provider,omitempty"`
	// SignedPayload holds the value of the "signed_payload" field.
	SignedPayload map[string]interface{} `json:"signed_payload,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentFactQuery when eager-loading is set.
	Edges                 PaymentFactEdges `json:"edges"`
	payment_attempt_facts *string
	selectValues          sql.SelectValues
}

// PaymentFactEdges holds the relations/edges for other nodes in the graph.
type PaymentFactEdges struct {
	// Attempt holds the value of the attempt edge.
	Attempt *PaymentAttempt `json:"attempt,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AttemptOrErr returns the Attempt value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentFactEdges) AttemptOrErr() (*PaymentAttempt, error) {
	if e.Attempt != nil {
		return e.Attempt, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentattempt.Label}
	}
	return nil, &NotLoadedError{edge: "attempt"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentFact) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentfact.FieldSignedPayload:
			values[i] = new([]byte)
		case paymentfact.FieldID, paymentfact.FieldNamespace, paymentfact.FieldRawHash, paymentfact.FieldProvider:
			values[i] = new(sql.NullString)
		case paymentfact.FieldCreatedAt, paymentfact.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case paymentfact.ForeignKeys[0]: // payment_attempt_facts
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentFact fields.
func (_m *PaymentFact) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentfact.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case paymentfact.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case paymentfact.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentfact.FieldRawHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_hash", values[i])
			} else if value.Valid {
				_m.RawHash = value.String
			}
		case paymentfact.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = paymentfact.Provider(value.String)
			}
		case paymentfact.FieldSignedPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field signed_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SignedPayload); err != nil {
					return fmt.Errorf("unmarshal field signed_payload: %w", err)
				}
			}
		case paymentfact.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case paymentfact.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_attempt_facts", values[i])
			} else if value.Valid {
				_m.payment_attempt_facts = new(string)
				*_m.payment_attempt_facts = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentFact.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentFact) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttempt queries the "attempt" edge of the PaymentFact entity.
func (_m *PaymentFact) QueryAttempt() *PaymentAttemptQuery {
	return NewPaymentFactClient(_m.config).QueryAttempt(_m)
}

// Update returns a builder for updating this PaymentFact.
// Note that you need to call PaymentFact.Unwrap() before calling this method if this PaymentFact
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentFact) Update() *PaymentFactUpdateOne {
	return NewPaymentFactClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentFact entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentFact) Unwrap() *PaymentFact {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: PaymentFact is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentFact) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentFact(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("raw_hash=")
	builder.WriteString(_m.RawHash)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("signed_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignedPayload))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentFacts is a parsable slice of PaymentFact.
type PaymentFacts []*PaymentFact
