// Code generated by ent, DO NOT EDIT.

package refundrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldDeletedAt, v))
}

// CommerceOrderID applies equality check predicate on the "commerce_order_id" field. It's identical to CommerceOrderIDEQ.
func CommerceOrderID(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCommerceOrderID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCustomerID, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAmountCents, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCurrency, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldReason, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldIdempotencyKey, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotNull(FieldDeletedAt))
}

// CommerceOrderIDEQ applies the EQ predicate on the "commerce_order_id" field.
func CommerceOrderIDEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCommerceOrderID, v))
}

// CommerceOrderIDNEQ applies the NEQ predicate on the "commerce_order_id" field.
func CommerceOrderIDNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldCommerceOrderID, v))
}

// CommerceOrderIDIn applies the In predicate on the "commerce_order_id" field.
func CommerceOrderIDIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldCommerceOrderID, vs...))
}

// CommerceOrderIDNotIn applies the NotIn predicate on the "commerce_order_id" field.
func CommerceOrderIDNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldCommerceOrderID, vs...))
}

// CommerceOrderIDGT applies the GT predicate on the "commerce_order_id" field.
func CommerceOrderIDGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldCommerceOrderID, v))
}

// CommerceOrderIDGTE applies the GTE predicate on the "commerce_order_id" field.
func CommerceOrderIDGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldCommerceOrderID, v))
}

// CommerceOrderIDLT applies the LT predicate on the "commerce_order_id" field.
func CommerceOrderIDLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldCommerceOrderID, v))
}

// CommerceOrderIDLTE applies the LTE predicate on the "commerce_order_id" field.
func CommerceOrderIDLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldCommerceOrderID, v))
}

// CommerceOrderIDContains applies the Contains predicate on the "commerce_order_id" field.
func CommerceOrderIDContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldCommerceOrderID, v))
}

// CommerceOrderIDHasPrefix applies the HasPrefix predicate on the "commerce_order_id" field.
func CommerceOrderIDHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldCommerceOrderID, v))
}

// CommerceOrderIDHasSuffix applies the HasSuffix predicate on the "commerce_order_id" field.
func CommerceOrderIDHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldCommerceOrderID, v))
}

// CommerceOrderIDEqualFold applies the EqualFold predicate on the "commerce_order_id" field.
func CommerceOrderIDEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldCommerceOrderID, v))
}

// CommerceOrderIDContainsFold applies the ContainsFold predicate on the "commerce_order_id" field.
func CommerceOrderIDContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldCommerceOrderID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldCustomerID, v))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldAmountCents, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldReason, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.RefundRequest {
	return predicate.RefundRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.CommerceOrder) predicate.RefundRequest {
	return predicate.RefundRequest(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFacts applies the HasEdge predicate on the "facts" edge.
func HasFacts() predicate.RefundRequest {
	return predicate.RefundRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FactsTable, FactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFactsWith applies the HasEdge predicate on the "facts" edge with a given conditions (other predicates).
func HasFactsWith(preds ...predicate.RefundFact) predicate.RefundRequest {
	return predicate.RefundRequest(func(s *sql.Selector) {
		step := newFactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RefundRequest) predicate.RefundRequest {
	return predicate.RefundRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RefundRequest) predicate.RefundRequest {
	return predicate.RefundRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RefundRequest) predicate.RefundRequest {
	return predicate.RefundRequest(sql.NotPredicates(p))
}
