// Code generated by ent, DO NOT EDIT.

package aiusagewatermark

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldSubjectID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldCustomerID, v))
}

// CoveredSeq applies equality check predicate on the "covered_seq" field. It's identical to CoveredSeqEQ.
func CoveredSeq(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldCoveredSeq, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldSubjectID, v))
}

// SubjectIDContains applies the Contains predicate on the "subject_id" field.
func SubjectIDContains(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContains(FieldSubjectID, v))
}

// SubjectIDHasPrefix applies the HasPrefix predicate on the "subject_id" field.
func SubjectIDHasPrefix(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldHasPrefix(FieldSubjectID, v))
}

// SubjectIDHasSuffix applies the HasSuffix predicate on the "subject_id" field.
func SubjectIDHasSuffix(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldHasSuffix(FieldSubjectID, v))
}

// SubjectIDEqualFold applies the EqualFold predicate on the "subject_id" field.
func SubjectIDEqualFold(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEqualFold(FieldSubjectID, v))
}

// SubjectIDContainsFold applies the ContainsFold predicate on the "subject_id" field.
func SubjectIDContainsFold(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContainsFold(FieldSubjectID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldContainsFold(FieldCustomerID, v))
}

// CoveredSeqEQ applies the EQ predicate on the "covered_seq" field.
func CoveredSeqEQ(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldEQ(FieldCoveredSeq, v))
}

// CoveredSeqNEQ applies the NEQ predicate on the "covered_seq" field.
func CoveredSeqNEQ(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNEQ(FieldCoveredSeq, v))
}

// CoveredSeqIn applies the In predicate on the "covered_seq" field.
func CoveredSeqIn(vs ...int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldIn(FieldCoveredSeq, vs...))
}

// CoveredSeqNotIn applies the NotIn predicate on the "covered_seq" field.
func CoveredSeqNotIn(vs ...int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldNotIn(FieldCoveredSeq, vs...))
}

// CoveredSeqGT applies the GT predicate on the "covered_seq" field.
func CoveredSeqGT(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGT(FieldCoveredSeq, v))
}

// CoveredSeqGTE applies the GTE predicate on the "covered_seq" field.
func CoveredSeqGTE(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldGTE(FieldCoveredSeq, v))
}

// CoveredSeqLT applies the LT predicate on the "covered_seq" field.
func CoveredSeqLT(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLT(FieldCoveredSeq, v))
}

// CoveredSeqLTE applies the LTE predicate on the "covered_seq" field.
func CoveredSeqLTE(v int64) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.FieldLTE(FieldCoveredSeq, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AIUsageWatermark) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AIUsageWatermark) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AIUsageWatermark) predicate.AIUsageWatermark {
	return predicate.AIUsageWatermark(sql.NotPredicates(p))
}
