services:
  openmeter:
    environment:
      POSTGRES_URL: ${OPENMETER_E2E_POSTGRES_URL:-postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable}
  sink-worker:
    environment:
      POSTGRES_URL: ${OPENMETER_E2E_POSTGRES_URL:-postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable}
  billing-worker:
    environment:
      POSTGRES_URL: ${OPENMETER_E2E_POSTGRES_URL:-postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable}
