services:
  openmeter:
    environment:
      POSTGRES_URL: postgres://postgres:qwerdfpostgres!123@postgres:5432/postgres?sslmode=disable
  sink-worker:
    environment:
      POSTGRES_URL: postgres://postgres:qwerdfpostgres!123@postgres:5432/postgres?sslmode=disable
  billing-worker:
    environment:
      POSTGRES_URL: postgres://postgres:qwerdfpostgres!123@postgres:5432/postgres?sslmode=disable
