// Code generated by ent, DO NOT EDIT.

package externalinvoiceref

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldDeletedAt, v))
}

// ReceivablePeriodID applies equality check predicate on the "receivable_period_id" field. It's identical to ReceivablePeriodIDEQ.
func ReceivablePeriodID(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldReceivablePeriodID, v))
}

// InvoiceNumber applies equality check predicate on the "invoice_number" field. It's identical to InvoiceNumberEQ.
func InvoiceNumber(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldInvoiceNumber, v))
}

// InvoiceURL applies equality check predicate on the "invoice_url" field. It's identical to InvoiceURLEQ.
func InvoiceURL(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldInvoiceURL, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldIssuedAt, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotNull(FieldDeletedAt))
}

// ReceivablePeriodIDEQ applies the EQ predicate on the "receivable_period_id" field.
func ReceivablePeriodIDEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDNEQ applies the NEQ predicate on the "receivable_period_id" field.
func ReceivablePeriodIDNEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDIn applies the In predicate on the "receivable_period_id" field.
func ReceivablePeriodIDIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldReceivablePeriodID, vs...))
}

// ReceivablePeriodIDNotIn applies the NotIn predicate on the "receivable_period_id" field.
func ReceivablePeriodIDNotIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldReceivablePeriodID, vs...))
}

// ReceivablePeriodIDGT applies the GT predicate on the "receivable_period_id" field.
func ReceivablePeriodIDGT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDGTE applies the GTE predicate on the "receivable_period_id" field.
func ReceivablePeriodIDGTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDLT applies the LT predicate on the "receivable_period_id" field.
func ReceivablePeriodIDLT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDLTE applies the LTE predicate on the "receivable_period_id" field.
func ReceivablePeriodIDLTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDContains applies the Contains predicate on the "receivable_period_id" field.
func ReceivablePeriodIDContains(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContains(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDHasPrefix applies the HasPrefix predicate on the "receivable_period_id" field.
func ReceivablePeriodIDHasPrefix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasPrefix(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDHasSuffix applies the HasSuffix predicate on the "receivable_period_id" field.
func ReceivablePeriodIDHasSuffix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasSuffix(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDEqualFold applies the EqualFold predicate on the "receivable_period_id" field.
func ReceivablePeriodIDEqualFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEqualFold(FieldReceivablePeriodID, v))
}

// ReceivablePeriodIDContainsFold applies the ContainsFold predicate on the "receivable_period_id" field.
func ReceivablePeriodIDContainsFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContainsFold(FieldReceivablePeriodID, v))
}

// InvoiceNumberEQ applies the EQ predicate on the "invoice_number" field.
func InvoiceNumberEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberNEQ applies the NEQ predicate on the "invoice_number" field.
func InvoiceNumberNEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberIn applies the In predicate on the "invoice_number" field.
func InvoiceNumberIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberNotIn applies the NotIn predicate on the "invoice_number" field.
func InvoiceNumberNotIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberGT applies the GT predicate on the "invoice_number" field.
func InvoiceNumberGT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldInvoiceNumber, v))
}

// InvoiceNumberGTE applies the GTE predicate on the "invoice_number" field.
func InvoiceNumberGTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldInvoiceNumber, v))
}

// InvoiceNumberLT applies the LT predicate on the "invoice_number" field.
func InvoiceNumberLT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldInvoiceNumber, v))
}

// InvoiceNumberLTE applies the LTE predicate on the "invoice_number" field.
func InvoiceNumberLTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldInvoiceNumber, v))
}

// InvoiceNumberContains applies the Contains predicate on the "invoice_number" field.
func InvoiceNumberContains(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContains(FieldInvoiceNumber, v))
}

// InvoiceNumberHasPrefix applies the HasPrefix predicate on the "invoice_number" field.
func InvoiceNumberHasPrefix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasPrefix(FieldInvoiceNumber, v))
}

// InvoiceNumberHasSuffix applies the HasSuffix predicate on the "invoice_number" field.
func InvoiceNumberHasSuffix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasSuffix(FieldInvoiceNumber, v))
}

// InvoiceNumberEqualFold applies the EqualFold predicate on the "invoice_number" field.
func InvoiceNumberEqualFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEqualFold(FieldInvoiceNumber, v))
}

// InvoiceNumberContainsFold applies the ContainsFold predicate on the "invoice_number" field.
func InvoiceNumberContainsFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContainsFold(FieldInvoiceNumber, v))
}

// InvoiceURLEQ applies the EQ predicate on the "invoice_url" field.
func InvoiceURLEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldInvoiceURL, v))
}

// InvoiceURLNEQ applies the NEQ predicate on the "invoice_url" field.
func InvoiceURLNEQ(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldInvoiceURL, v))
}

// InvoiceURLIn applies the In predicate on the "invoice_url" field.
func InvoiceURLIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldInvoiceURL, vs...))
}

// InvoiceURLNotIn applies the NotIn predicate on the "invoice_url" field.
func InvoiceURLNotIn(vs ...string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldInvoiceURL, vs...))
}

// InvoiceURLGT applies the GT predicate on the "invoice_url" field.
func InvoiceURLGT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldInvoiceURL, v))
}

// InvoiceURLGTE applies the GTE predicate on the "invoice_url" field.
func InvoiceURLGTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldInvoiceURL, v))
}

// InvoiceURLLT applies the LT predicate on the "invoice_url" field.
func InvoiceURLLT(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldInvoiceURL, v))
}

// InvoiceURLLTE applies the LTE predicate on the "invoice_url" field.
func InvoiceURLLTE(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldInvoiceURL, v))
}

// InvoiceURLContains applies the Contains predicate on the "invoice_url" field.
func InvoiceURLContains(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContains(FieldInvoiceURL, v))
}

// InvoiceURLHasPrefix applies the HasPrefix predicate on the "invoice_url" field.
func InvoiceURLHasPrefix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasPrefix(FieldInvoiceURL, v))
}

// InvoiceURLHasSuffix applies the HasSuffix predicate on the "invoice_url" field.
func InvoiceURLHasSuffix(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldHasSuffix(FieldInvoiceURL, v))
}

// InvoiceURLIsNil applies the IsNil predicate on the "invoice_url" field.
func InvoiceURLIsNil() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIsNull(FieldInvoiceURL))
}

// InvoiceURLNotNil applies the NotNil predicate on the "invoice_url" field.
func InvoiceURLNotNil() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotNull(FieldInvoiceURL))
}

// InvoiceURLEqualFold applies the EqualFold predicate on the "invoice_url" field.
func InvoiceURLEqualFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEqualFold(FieldInvoiceURL, v))
}

// InvoiceURLContainsFold applies the ContainsFold predicate on the "invoice_url" field.
func InvoiceURLContainsFold(v string) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldContainsFold(FieldInvoiceURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldStatus, vs...))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.FieldNotNull(FieldIssuedAt))
}

// HasPeriod applies the HasEdge predicate on the "period" edge.
func HasPeriod() predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PeriodTable, PeriodColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPeriodWith applies the HasEdge predicate on the "period" edge with a given conditions (other predicates).
func HasPeriodWith(preds ...predicate.ReceivablePeriod) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(func(s *sql.Selector) {
		step := newPeriodStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalInvoiceRef) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalInvoiceRef) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalInvoiceRef) predicate.ExternalInvoiceRef {
	return predicate.ExternalInvoiceRef(sql.NotPredicates(p))
}
