// Code generated by ent, DO NOT EDIT.

package creditcharge

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the creditcharge type in the database.
	Label = "credit_charge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldReservationID holds the string denoting the reservation_id field in the database.
	FieldReservationID = "reservation_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldSubjectID holds the string denoting the subject_id field in the database.
	FieldSubjectID = "subject_id"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldPayloadHash holds the string denoting the payload_hash field in the database.
	FieldPayloadHash = "payload_hash"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldCustomCurrencyID holds the string denoting the custom_currency_id field in the database.
	FieldCustomCurrencyID = "custom_currency_id"
	// FieldRatedLines holds the string denoting the rated_lines field in the database.
	FieldRatedLines = "rated_lines"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldSettlementLedgerGroupID holds the string denoting the settlement_ledger_group_id field in the database.
	FieldSettlementLedgerGroupID = "settlement_ledger_group_id"
	// FieldReversalLedgerGroupID holds the string denoting the reversal_ledger_group_id field in the database.
	FieldReversalLedgerGroupID = "reversal_ledger_group_id"
	// FieldUsageEventID holds the string denoting the usage_event_id field in the database.
	FieldUsageEventID = "usage_event_id"
	// Table holds the table name of the creditcharge in the database.
	Table = "credit_charges"
)

// Columns holds all SQL columns for creditcharge fields.
var Columns = []string{
	FieldID,
	FieldNamespace,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldReservationID,
	FieldCustomerID,
	FieldSubjectID,
	FieldOperation,
	FieldIdempotencyKey,
	FieldPayloadHash,
	FieldCurrency,
	FieldCustomCurrencyID,
	FieldRatedLines,
	FieldAmount,
	FieldState,
	FieldSettlementLedgerGroupID,
	FieldReversalLedgerGroupID,
	FieldUsageEventID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	NamespaceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	CustomerIDValidator func(string) error
	// SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	SubjectIDValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	PayloadHashValidator func(string) error
	// DefaultSettlementLedgerGroupID holds the default value on creation for the "settlement_ledger_group_id" field.
	DefaultSettlementLedgerGroupID string
	// DefaultReversalLedgerGroupID holds the default value on creation for the "reversal_ledger_group_id" field.
	DefaultReversalLedgerGroupID string
	// DefaultUsageEventID holds the default value on creation for the "usage_event_id" field.
	DefaultUsageEventID string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// State defines the type for the "state" enum field.
type State string

// State values.
const (
	StateSETTLED  State = "SETTLED"
	StateREVERSED State = "REVERSED"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateSETTLED, StateREVERSED:
		return nil
	default:
		return fmt.Errorf("creditcharge: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the CreditCharge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByReservationID orders the results by the reservation_id field.
func ByReservationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// BySubjectID orders the results by the subject_id field.
func BySubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectID, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByPayloadHash orders the results by the payload_hash field.
func ByPayloadHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadHash, opts...).ToFunc()
}

// ByCustomCurrencyID orders the results by the custom_currency_id field.
func ByCustomCurrencyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomCurrencyID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// BySettlementLedgerGroupID orders the results by the settlement_ledger_group_id field.
func BySettlementLedgerGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementLedgerGroupID, opts...).ToFunc()
}

// ByReversalLedgerGroupID orders the results by the reversal_ledger_group_id field.
func ByReversalLedgerGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversalLedgerGroupID, opts...).ToFunc()
}

// ByUsageEventID orders the results by the usage_event_id field.
func ByUsageEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageEventID, opts...).ToFunc()
}
