// Code generated by ent, DO NOT EDIT.

package customerairatepackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldDeletedAt, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldCustomerID, v))
}

// PackageCode applies equality check predicate on the "package_code" field. It's identical to PackageCodeEQ.
func PackageCode(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldPackageCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldDescription, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveTo applies equality check predicate on the "effective_to" field. It's identical to EffectiveToEQ.
func EffectiveTo(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldEffectiveTo, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContainsFold(FieldNamespace, v))
}

// AnnotationsIsNil applies the IsNil predicate on the "annotations" field.
func AnnotationsIsNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIsNull(FieldAnnotations))
}

// AnnotationsNotNil applies the NotNil predicate on the "annotations" field.
func AnnotationsNotNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotNull(FieldAnnotations))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotNull(FieldDeletedAt))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContainsFold(FieldCustomerID, v))
}

// PackageCodeEQ applies the EQ predicate on the "package_code" field.
func PackageCodeEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldPackageCode, v))
}

// PackageCodeNEQ applies the NEQ predicate on the "package_code" field.
func PackageCodeNEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldPackageCode, v))
}

// PackageCodeIn applies the In predicate on the "package_code" field.
func PackageCodeIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldPackageCode, vs...))
}

// PackageCodeNotIn applies the NotIn predicate on the "package_code" field.
func PackageCodeNotIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldPackageCode, vs...))
}

// PackageCodeGT applies the GT predicate on the "package_code" field.
func PackageCodeGT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldPackageCode, v))
}

// PackageCodeGTE applies the GTE predicate on the "package_code" field.
func PackageCodeGTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldPackageCode, v))
}

// PackageCodeLT applies the LT predicate on the "package_code" field.
func PackageCodeLT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldPackageCode, v))
}

// PackageCodeLTE applies the LTE predicate on the "package_code" field.
func PackageCodeLTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldPackageCode, v))
}

// PackageCodeContains applies the Contains predicate on the "package_code" field.
func PackageCodeContains(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContains(FieldPackageCode, v))
}

// PackageCodeHasPrefix applies the HasPrefix predicate on the "package_code" field.
func PackageCodeHasPrefix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasPrefix(FieldPackageCode, v))
}

// PackageCodeHasSuffix applies the HasSuffix predicate on the "package_code" field.
func PackageCodeHasSuffix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasSuffix(FieldPackageCode, v))
}

// PackageCodeEqualFold applies the EqualFold predicate on the "package_code" field.
func PackageCodeEqualFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEqualFold(FieldPackageCode, v))
}

// PackageCodeContainsFold applies the ContainsFold predicate on the "package_code" field.
func PackageCodeContainsFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContainsFold(FieldPackageCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldStatus, vs...))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveToEQ applies the EQ predicate on the "effective_to" field.
func EffectiveToEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldEQ(FieldEffectiveTo, v))
}

// EffectiveToNEQ applies the NEQ predicate on the "effective_to" field.
func EffectiveToNEQ(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNEQ(FieldEffectiveTo, v))
}

// EffectiveToIn applies the In predicate on the "effective_to" field.
func EffectiveToIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIn(FieldEffectiveTo, vs...))
}

// EffectiveToNotIn applies the NotIn predicate on the "effective_to" field.
func EffectiveToNotIn(vs ...time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotIn(FieldEffectiveTo, vs...))
}

// EffectiveToGT applies the GT predicate on the "effective_to" field.
func EffectiveToGT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGT(FieldEffectiveTo, v))
}

// EffectiveToGTE applies the GTE predicate on the "effective_to" field.
func EffectiveToGTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldGTE(FieldEffectiveTo, v))
}

// EffectiveToLT applies the LT predicate on the "effective_to" field.
func EffectiveToLT(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLT(FieldEffectiveTo, v))
}

// EffectiveToLTE applies the LTE predicate on the "effective_to" field.
func EffectiveToLTE(v time.Time) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldLTE(FieldEffectiveTo, v))
}

// EffectiveToIsNil applies the IsNil predicate on the "effective_to" field.
func EffectiveToIsNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldIsNull(FieldEffectiveTo))
}

// EffectiveToNotNil applies the NotNil predicate on the "effective_to" field.
func EffectiveToNotNil() predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.FieldNotNull(FieldEffectiveTo))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerAIRatePackage) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerAIRatePackage) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerAIRatePackage) predicate.CustomerAIRatePackage {
	return predicate.CustomerAIRatePackage(sql.NotPredicates(p))
}
