// Code generated by ent, DO NOT EDIT.

package paymentfact

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldCreatedAt, v))
}

// RawHash applies equality check predicate on the "raw_hash" field. It's identical to RawHashEQ.
func RawHash(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldRawHash, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldTimestamp, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLTE(FieldCreatedAt, v))
}

// RawHashEQ applies the EQ predicate on the "raw_hash" field.
func RawHashEQ(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldRawHash, v))
}

// RawHashNEQ applies the NEQ predicate on the "raw_hash" field.
func RawHashNEQ(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNEQ(FieldRawHash, v))
}

// RawHashIn applies the In predicate on the "raw_hash" field.
func RawHashIn(vs ...string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldIn(FieldRawHash, vs...))
}

// RawHashNotIn applies the NotIn predicate on the "raw_hash" field.
func RawHashNotIn(vs ...string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNotIn(FieldRawHash, vs...))
}

// RawHashGT applies the GT predicate on the "raw_hash" field.
func RawHashGT(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGT(FieldRawHash, v))
}

// RawHashGTE applies the GTE predicate on the "raw_hash" field.
func RawHashGTE(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGTE(FieldRawHash, v))
}

// RawHashLT applies the LT predicate on the "raw_hash" field.
func RawHashLT(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLT(FieldRawHash, v))
}

// RawHashLTE applies the LTE predicate on the "raw_hash" field.
func RawHashLTE(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLTE(FieldRawHash, v))
}

// RawHashContains applies the Contains predicate on the "raw_hash" field.
func RawHashContains(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldContains(FieldRawHash, v))
}

// RawHashHasPrefix applies the HasPrefix predicate on the "raw_hash" field.
func RawHashHasPrefix(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldHasPrefix(FieldRawHash, v))
}

// RawHashHasSuffix applies the HasSuffix predicate on the "raw_hash" field.
func RawHashHasSuffix(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldHasSuffix(FieldRawHash, v))
}

// RawHashEqualFold applies the EqualFold predicate on the "raw_hash" field.
func RawHashEqualFold(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEqualFold(FieldRawHash, v))
}

// RawHashContainsFold applies the ContainsFold predicate on the "raw_hash" field.
func RawHashContainsFold(v string) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldContainsFold(FieldRawHash, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNotIn(FieldProvider, vs...))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.PaymentFact {
	return predicate.PaymentFact(sql.FieldLTE(FieldTimestamp, v))
}

// HasAttempt applies the HasEdge predicate on the "attempt" edge.
func HasAttempt() predicate.PaymentFact {
	return predicate.PaymentFact(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AttemptTable, AttemptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptWith applies the HasEdge predicate on the "attempt" edge with a given conditions (other predicates).
func HasAttemptWith(preds ...predicate.PaymentAttempt) predicate.PaymentFact {
	return predicate.PaymentFact(func(s *sql.Selector) {
		step := newAttemptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentFact) predicate.PaymentFact {
	return predicate.PaymentFact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentFact) predicate.PaymentFact {
	return predicate.PaymentFact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentFact) predicate.PaymentFact {
	return predicate.PaymentFact(sql.NotPredicates(p))
}
