// Code generated by @openmeter/typespec-typescript. DO NOT EDIT.

import type { NamespaceList } from '../types.js'

export type ListNamespacesRequest = Record<string, never>
export type ListNamespacesResponse = NamespaceList
